import type { AlertRule } from "@shared/alerts";

function rule(input: Omit<AlertRule, "bypassGlobalCooldown" | "desktopOnly"> & Partial<Pick<AlertRule, "bypassGlobalCooldown" | "desktopOnly">>): AlertRule {
  return {
    bypassGlobalCooldown: false,
    desktopOnly: false,
    ...input,
  };
}

export const ALERT_RULES: Record<string, AlertRule> = {
  "gamma.regime_changed": rule({
    type: "gamma.regime_changed",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.flip_approaching": rule({
    type: "gamma.flip_approaching",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    expiresAfterMs: 45 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.flip_crossed": rule({
    type: "gamma.flip_crossed",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 15 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.transition_entered": rule({
    type: "gamma.transition_entered",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    expiresAfterMs: 45 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.transition_exited": rule({
    type: "gamma.transition_exited",
    domain: "gamma",
    defaultSeverity: "P3",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    expiresAfterMs: 30 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.call_wall_approaching": rule({
    type: "gamma.call_wall_approaching",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    expiresAfterMs: 45 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.call_wall_touched": rule({
    type: "gamma.call_wall_touched",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.call_wall_broken": rule({
    type: "gamma.call_wall_broken",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.put_wall_approaching": rule({
    type: "gamma.put_wall_approaching",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    expiresAfterMs: 45 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.put_wall_touched": rule({
    type: "gamma.put_wall_touched",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.put_wall_broken": rule({
    type: "gamma.put_wall_broken",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.dealer_pivot_approaching": rule({
    type: "gamma.dealer_pivot_approaching",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    expiresAfterMs: 45 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.dealer_pivot_crossed": rule({
    type: "gamma.dealer_pivot_crossed",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.magnet_approaching": rule({
    type: "gamma.magnet_approaching",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 35 * 60_000,
    expiresAfterMs: 45 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.short_gamma_pocket_entered": rule({
    type: "gamma.short_gamma_pocket_entered",
    domain: "gamma",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.total_gex_shift": rule({
    type: "gamma.total_gex_shift",
    domain: "gamma",
    defaultSeverity: "P2",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 45 * 60_000,
    expiresAfterMs: 60 * 60_000,
    requiresAcknowledgement: false,
  }),
  "gamma.dominant_expiry_changed": rule({
    type: "gamma.dominant_expiry_changed",
    domain: "gamma",
    defaultSeverity: "P3",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 60 * 60_000,
    expiresAfterMs: 60 * 60_000,
    requiresAcknowledgement: false,
  }),
  "market.squeeze_risk_increased": rule({
    type: "market.squeeze_risk_increased",
    domain: "market",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 25 * 60_000,
    requiresAcknowledgement: false,
  }),
  "market.cascade_risk_increased": rule({
    type: "market.cascade_risk_increased",
    domain: "market",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 25 * 60_000,
    requiresAcknowledgement: false,
  }),
  "system.data_source_down": rule({
    type: "system.data_source_down",
    domain: "system",
    defaultSeverity: "P0",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 5 * 60_000,
    requiresAcknowledgement: true,
    bypassGlobalCooldown: true,
  }),
  "system.data_source_restored": rule({
    type: "system.data_source_restored",
    domain: "system",
    defaultSeverity: "P3",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 5 * 60_000,
    expiresAfterMs: 30 * 60_000,
    requiresAcknowledgement: false,
  }),
  "system.stale_data": rule({
    type: "system.stale_data",
    domain: "system",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 10 * 60_000,
    requiresAcknowledgement: false,
  }),
  "system.update_available": rule({
    type: "system.update_available",
    domain: "system",
    defaultSeverity: "P4",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 24 * 60 * 60_000,
    expiresAfterMs: 7 * 24 * 60 * 60_000,
    requiresAcknowledgement: false,
  }),
  "system.subscription_expiring": rule({
    type: "system.subscription_expiring",
    domain: "system",
    defaultSeverity: "P4",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 24 * 60 * 60_000,
    expiresAfterMs: 7 * 24 * 60 * 60_000,
    requiresAcknowledgement: false,
  }),
  "system.subscription_expired": rule({
    type: "system.subscription_expired",
    domain: "system",
    defaultSeverity: "P0",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 60 * 60_000,
    requiresAcknowledgement: true,
    bypassGlobalCooldown: true,
  }),
  "system.auth_expired": rule({
    type: "system.auth_expired",
    domain: "system",
    defaultSeverity: "P0",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 30 * 60_000,
    requiresAcknowledgement: true,
    bypassGlobalCooldown: true,
  }),
  "account.connection_lost": rule({
    type: "account.connection_lost",
    domain: "account",
    defaultSeverity: "P0",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 5 * 60_000,
    requiresAcknowledgement: true,
    bypassGlobalCooldown: true,
  }),
  "account.connection_restored": rule({
    type: "account.connection_restored",
    domain: "account",
    defaultSeverity: "P3",
    defaultChannels: ["in_app"],
    enabledByDefault: true,
    cooldownMs: 5 * 60_000,
    expiresAfterMs: 30 * 60_000,
    requiresAcknowledgement: false,
  }),
  "account.api_permission_error": rule({
    type: "account.api_permission_error",
    domain: "account",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: true,
    cooldownMs: 15 * 60_000,
    requiresAcknowledgement: false,
  }),
  "flow.large_absorption_detected": rule({
    type: "flow.large_absorption_detected",
    domain: "flow",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: false,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
    desktopOnly: true,
    featureFlag: "ALERTS_FLOW_ENABLED",
  }),
  "flow.aggression_spike": rule({
    type: "flow.aggression_spike",
    domain: "flow",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: false,
    cooldownMs: 20 * 60_000,
    requiresAcknowledgement: false,
    desktopOnly: true,
    featureFlag: "ALERTS_FLOW_ENABLED",
  }),
  "flow.spoofing_suspected": rule({
    type: "flow.spoofing_suspected",
    domain: "flow",
    defaultSeverity: "P1",
    defaultChannels: ["in_app", "desktop_native"],
    enabledByDefault: false,
    cooldownMs: 45 * 60_000,
    requiresAcknowledgement: false,
    desktopOnly: true,
    featureFlag: "ALERTS_FLOW_ENABLED",
  }),
};

export const DISABLED_FLOW_ALERT_TYPES = [
  "flow.passive_wall_appeared",
  "flow.passive_wall_removed",
  "flow.passive_wall_pulled",
  "flow.iceberg_suspected",
  "flow.sweep_detected",
  "flow.spot_perp_divergence",
  "flow.cvd_divergence",
];

export function getAlertRule(type: string): AlertRule | undefined {
  return ALERT_RULES[type];
}
