import type { AcademyContentBlock } from "@shared/academy-content";

const content = (blocks: AcademyContentBlock[]): AcademyContentBlock[] => blocks;
const source = (text: string): AcademyContentBlock => ({ type: "callout", title: "Procedencia", text });

export const GAMMA_AND_DEALER_HEDGING_CONTENT: Record<string, AcademyContentBlock[]> = {
  "gamma-and-dealer-hedging-01-what-is-gamma": content([
    { type: "heading", level: 2, text: "La velocidad de cambio de Delta" },
    { type: "paragraph", text: "Gamma describe cuánto puede cambiar Delta ante un cambio del subyacente. Si Delta es una sensibilidad local, Gamma describe la curvatura de esa sensibilidad: una Gamma mayor implica que la exposición direccional puede cambiar más rápido cuando cambia el precio, manteniendo conceptualmente controladas otras variables." },
    { type: "paragraph", text: "Esta relación importa para la cobertura. Si la Delta de una cartera cambia, una cobertura que era razonable hace unos minutos puede dejar de compensar la misma exposición. El ajuste depende del contrato, el tamaño, el tiempo, la volatilidad y la posición completa; Gamma no indica por sí sola qué debe hacer el precio." },
    { type: "list", items: ["Gamma es una sensibilidad calculada, no una operación observada.", "Su magnitud depende de spot, strike, IV y tiempo a expiración.", "La Gamma de una cartera es la suma de exposiciones bajo una convención.", "Una alta Gamma puede aumentar la velocidad con que cambia la necesidad de cobertura."] },
    source("El instrumento, strike, expiry, OI, IV y spot son datos recibidos cuando están disponibles. Gamma y sus agregaciones son métricas derivadas; no son inventario de dealers observado."),
  ]),
  "gamma-and-dealer-hedging-02-long-gamma": content([
    { type: "heading", level: 2, text: "Una propiedad de posición" },
    { type: "paragraph", text: "Una posición long Gamma tiene una Delta que tiende a aumentar cuando sube el subyacente y a disminuir cuando baja, bajo la convención y el modelo aplicados. Esa dinámica puede hacer que una cobertura compensatoria se ajuste en sentido contrario al movimiento que generó el cambio de Delta." },
    { type: "paragraph", text: "Long Gamma describe una exposición, no la identidad de quien la mantiene. Una cadena con OI no revela automáticamente si el dealer, el cliente u otro participante está long Gamma. Para hablar de exposición agregada hay que declarar universo, signo, vencimiento y datos disponibles." },
    { type: "list", items: ["La relación es local y cambia con spot, IV y tiempo.", "La cobertura puede reducir una parte de la exposición, pero no elimina todos los riesgos.", "Long Gamma no equivale a mercado bajista ni a reversión garantizada.", "Otros flujos pueden dominar la respuesta observada."] },
    source("Long Gamma es una interpretación derivada de una posición/modelo. No es una observación directa de la cartera real de un participante."),
  ]),
  "gamma-and-dealer-hedging-03-short-gamma": content([
    { type: "heading", level: 2, text: "Cuando la sensibilidad tiene el signo inverso" },
    { type: "paragraph", text: "Una posición short Gamma tiene una Delta que tiende a cambiar en sentido contrario al caso long Gamma cuando se mueve el subyacente. Bajo determinados supuestos de cobertura, el ajuste necesario puede alinearse con el movimiento que ya ocurrió y aumentar la sensibilidad de la cartera al desplazamiento." },
    { type: "paragraph", text: "Eso no convierte short Gamma en una explicación completa de una aceleración. El resultado depende de cómo se cubre la cartera, qué instrumentos se usan, qué parte del universo se observa y qué ocurre con liquidez, futuros, perpetuals, spot, noticias y volatilidad." },
    { type: "list", items: ["Short Gamma es una propiedad/modelo de exposición.", "No demuestra que el precio vaya a explotar.", "No identifica automáticamente un dealer short Gamma.", "La respuesta real debe contrastarse con ejecución y liquidez observables."] },
    source("La etiqueta short Gamma pertenece a una capa derivada o estructural. No describe trades de dealers observados."),
  ]),
  "gamma-and-dealer-hedging-04-positive-gamma": content([
    { type: "heading", level: 2, text: "El signo positivo en el modelo" },
    { type: "paragraph", text: "En GoodTrading, Positive Gamma se utiliza para describir un régimen de exposición Gamma agregada con signo positivo bajo la convención implementada. En ciertos escenarios, ese contexto puede ser consistente con respuestas de cobertura más estabilizadoras: ajustes que tienden a oponerse parcialmente al movimiento del subyacente." },
    { type: "paragraph", text: "Positive Gamma no significa bearish, no obliga al precio a caer y no garantiza mean reversion. El signo depende del universo de opciones, la IV, el OI, el contract size, el spot y la convención call/put utilizada por el modelo." },
    { type: "list", items: ["Régimen positivo no equivale a dirección futura.", "Una cobertura modelada no es una ejecución observada.", "Un cambio de fuente o de universo puede cambiar el régimen.", "La lectura debe conservar la calidad y frescura del dato."] },
    source("Positive Gamma es un régimen derivado/modelado. Calls positivas y puts negativas son una convención estructural, no una prueba de lado dealer."),
  ]),
  "gamma-and-dealer-hedging-05-negative-gamma": content([
    { type: "heading", level: 2, text: "El signo negativo en el modelo" },
    { type: "paragraph", text: "Negative Gamma describe un régimen de exposición agregada con signo negativo bajo la convención del modelo. En algunos escenarios, los ajustes de cobertura modelados pueden ser más pro-cíclicos o amplificar el desplazamiento ya observado." },
    { type: "paragraph", text: "Negative Gamma no significa bullish, no garantiza tendencia y no es una señal de breakout. La magnitud y utilidad del resultado dependen de inputs válidos, expiries incluidas, strike band, IV, OI, spot y de los flujos que no forman parte de la superficie de opciones." },
    { type: "list", items: ["El régimen no predice dirección.", "La presión estimada puede quedar neutralizada por otros participantes.", "No confundas Gamma negativa con posición short observada de un dealer.", "Si la fuente es bootstrap o no-data, la lectura no debe llamarse live."] },
    source("Negative Gamma es un resultado derivado/modelado, no un registro de operaciones ni inventario dealer observado."),
  ]),
  "gamma-and-dealer-hedging-06-dealer-positioning": content([
    { type: "heading", level: 2, text: "Posicionamiento inferido" },
    { type: "paragraph", text: "GoodTrading no observa el inventario completo de cada dealer. Construye un proxy a partir de datos de opciones y supuestos sobre cómo asignar signo a contribuciones de calls y puts. El proxy puede ser útil para organizar hipótesis, pero no convierte OI en identidad de participante." },
    { type: "paragraph", text: "El modelo usa strike, expiración, tipo de opción, OI, IV y spot. La convención actual asigna contribución positiva a calls y negativa a puts para agregaciones como GEX, Vanna y Charm. Esa elección es estructural: no prueba que los clientes sean siempre compradores ni que los dealers sean siempre vendedores." },
    { type: "list", items: ["Observado: contrato, strike, expiry, OI, IV y spot cuando existen.", "Derivado: Gamma, GEX y sensibilidades agregadas.", "Proxy: signo dealer y presión de cobertura.", "Una sola venue no representa todo el posicionamiento del mercado."] },
    source("Dealer positioning es una inferencia. La fuente no contiene una columna que observe directamente el lado real del dealer."),
  ]),
  "gamma-and-dealer-hedging-07-delta-neutrality": content([
    { type: "heading", level: 2, text: "Neutralidad como objetivo dinámico" },
    { type: "paragraph", text: "Una cartera puede intentar reducir su Delta neta usando el subyacente, futuros, perpetuals u otros instrumentos relacionados. Delta neutrality es una condición local y temporal: que una cartera esté cerca de neutral ahora no implica que permanezca neutral cuando cambien spot, IV, tiempo o sus posiciones." },
    { type: "paragraph", text: "La neutralidad tampoco es una propiedad universal de todos los dealers. Cada participante puede tener objetivos, límites, inventario, costes y horizontes diferentes. El modelo de hedge pressure representa una necesidad estimada bajo supuestos, no una confirmación de que alguien esté ejecutando el hedge." },
    { type: "list", items: ["Delta neutral no elimina Gamma, Vega, Theta, Vanna, Charm ni liquidez.", "La cobertura puede ser parcial, discreta o imperfecta.", "El instrumento usado para cubrir introduce basis y riesgo de ejecución.", "No infieras neutralidad real desde una etiqueta de régimen."] },
    source("La neutralidad es un estado/objetivo modelado. Las ejecuciones concretas de cobertura no forman parte del dato observado por este contrato."),
  ]),
  "gamma-and-dealer-hedging-08-hedging-when-price-rises": content([
    { type: "heading", level: 2, text: "Un escenario condicionado" },
    { type: "paragraph", text: "Cuando sube el precio, cambia la Delta de las opciones y puede cambiar la cantidad de subyacente necesaria para compensar una cartera. La dirección del ajuste depende de la posición Gamma, del signo de la exposición, de la cartera completa y de la convención usada por el modelo." },
    { type: "paragraph", text: "Por eso no es correcto afirmar que los dealers siempre compran cuando sube el precio. Bajo una estructura puede estimarse presión compradora; bajo otra, presión vendedora; y con datos insuficientes puede no haber una conclusión disponible." },
    { type: "list", items: ["Primero identifica el cambio de Delta.", "Luego declara el supuesto de posición y cobertura.", "Separa hedge requerido estimado de ejecución real.", "Contrasta el escenario con liquidez y flujo observado."] },
    source("El modelo puede estimar hedge pressure ante un shock, pero no observa quién ejecutó una compra o venta."),
  ]),
  "gamma-and-dealer-hedging-09-hedging-when-price-falls": content([
    { type: "heading", level: 2, text: "La misma lógica en sentido contrario" },
    { type: "paragraph", text: "Una caída del spot también modifica Delta, Gamma efectiva y el hedge requerido. La respuesta depende de si la exposición es long o short Gamma bajo el modelo y de cómo están combinadas las expiries, strikes y sensibilidades." },
    { type: "paragraph", text: "No es correcto afirmar que los dealers siempre venden cuando cae el precio. La estructura puede ser consistente con comprar para compensar, vender para seguir la exposición o no producir una señal útil si faltan datos o dominan otros flujos." },
    { type: "list", items: ["El signo del ajuste se deriva de la cartera supuesta.", "Spot, IV y tiempo cambian simultáneamente.", "Una caída observada no prueba un hedge dealer específico.", "La evidencia de ejecución pertenece a Order Flow, no a GEX."] },
    source("La dirección de hedge en este marco es una salida modelada y condicionada, no un hecho observado de mercado."),
  ]),
  "gamma-and-dealer-hedging-10-stabilizing-flows": content([
    { type: "heading", level: 2, text: "Presión que puede amortiguar" },
    { type: "paragraph", text: "Algunas configuraciones de Gamma son consistentes con ajustes de cobertura que se oponen parcialmente al movimiento del subyacente. Bajo el modelo, esa presión puede contribuir a amortiguar desplazamientos o favorecer una negociación más contenida alrededor de determinadas zonas." },
    { type: "paragraph", text: "Estabilizante no significa que el precio deba volver a la media. Noticias, spot flow, futuros, perpetuals, liquidez retirada y cambios de IV pueden dominar la respuesta. La etiqueta resume un mecanismo hipotético, no una promesa de comportamiento." },
    { type: "list", items: ["Usa ‘puede contribuir a’, no ‘estabilizará’.", "Comprueba si la concentración es significativa y fresca.", "Observa si el precio realmente pierde continuidad.", "Mantén separadas estructura derivada y ejecución observada."] },
    source("Stabilizing flow es una interpretación estructural del hedge requerido, no un stream de órdenes dealer."),
  ]),
  "gamma-and-dealer-hedging-11-destabilizing-flows": content([
    { type: "heading", level: 2, text: "Presión que puede reforzar" },
    { type: "paragraph", text: "Otras configuraciones son consistentes con ajustes de cobertura que siguen el desplazamiento del precio. Bajo el modelo, esa presión puede contribuir a una mayor continuidad o aceleración, especialmente si coincide con liquidez frágil y ejecución agresiva." },
    { type: "paragraph", text: "Destabilizante no significa que el precio vaya a continuar. El modelo puede estar incompleto, el OI puede no representar todo el mercado y una respuesta pasiva puede absorber el movimiento. El régimen describe contexto, no dirección garantizada." },
    { type: "list", items: ["Separa amplificación modelada de aceleración observada.", "Busca evidencia de progreso y ejecución, no solo un color de régimen.", "Incluye macro, spot, futures, perpetuals y liquidez.", "Si hay fallback o no-data, no atribuyas presión al modelo."] },
    source("Destabilizing flow es una hipótesis derivada bajo supuestos de cobertura; no es una observación de ventas o compras dealer."),
  ]),
  "gamma-and-dealer-hedging-12-gamma-exposure": content([
    { type: "heading", level: 2, text: "De sensibilidad a exposición" },
    { type: "paragraph", text: "Gamma Exposure, o GEX, resume una estimación de cuánto puede importar la Gamma agregada de las opciones bajo una unidad de contrato y un spot determinados. En la implementación actual, la contribución incorpora Gamma, Open Interest, contract size y spot." },
    { type: "paragraph", text: "Conceptualmente, una contribución se aproxima como Gamma × OI × contract size × spot. El signo aplicado por el modelo es positivo para calls y negativo para puts. Ese signo ordena una hipótesis de exposición; no es una observación del lado dealer." },
    { type: "list", items: ["Gamma por opción es derivada de spot, strike, IV y tiempo.", "OI es un input recibido, no una lectura del dealer.", "GEX es una salida del modelo.", "La cobertura estimada depende del universo incluido."] },
    source("Observed: option rows y OI. Derived: Gamma y GEX. Model/proxy: signo call/put y lectura dealer."),
  ]),
  "gamma-and-dealer-hedging-13-aggregate-gex": content([
    { type: "heading", level: 2, text: "Un resumen que depende del universo" },
    { type: "paragraph", text: "Aggregate GEX suma contribuciones de contratos elegibles para construir un contexto de mercado. Esa suma puede ser útil como resumen, pero puede ocultar concentraciones opuestas por strike o expiración y no debe tratarse como una verdad única independiente de la selección." },
    { type: "list", items: ["La selección de expiries cambia el resultado.", "La strike band puede excluir parte de la superficie.", "IV faltante elimina contribuciones de ciertas filas.", "El spot de evaluación cambia la Gamma.", "La convención de signo y el tamaño de contrato importan."] },
    { type: "paragraph", text: "Dos modelos pueden calcular valores diferentes usando datos razonables si no comparten universo, timestamp, IV, normalización o supuestos de dealer. El número agregado necesita contexto antes de interpretarse." },
    source("Aggregate GEX es derivado y dependiente de procedencia. No es un volumen ejecutado ni una medición directa de inventario."),
  ]),
  "gamma-and-dealer-hedging-14-strike-gex": content([
    { type: "heading", level: 2, text: "Dónde se concentra la sensibilidad" },
    { type: "paragraph", text: "Strike GEX agrupa la exposición estimada alrededor de cada strike. Permite observar dónde el modelo encuentra mayor concentración de sensibilidad y comparar esa zona con spot, expiración y liquidez disponible." },
    { type: "paragraph", text: "Una concentración grande no es soporte ni resistencia garantizada. Un strike puede atravesarse, perder relevancia cuando cambia IV u OI, o tener una respuesta distinta según la expiración. La etiqueta ‘wall’ es una referencia estructural, no una barrera física." },
    { type: "list", items: ["Agrupar por strike conserva estructura local.", "No mezcles automáticamente expiries incompatibles.", "Distingue OI observado de GEX calculado.", "Contrasta la reacción real del precio con la hipótesis."] },
    source("Strike y OI son datos de la cadena; Strike GEX y walls son agregaciones derivadas/modeladas."),
  ]),
  "gamma-and-dealer-hedging-15-expiry-gex": content([
    { type: "heading", level: 2, text: "Cada vencimiento aporta un reloj distinto" },
    { type: "paragraph", text: "Expiry GEX agrupa o interpreta Gamma por fecha de expiración. El tiempo exacto restante afecta la sensibilidad, por lo que una expiración cercana y otra lejana no tienen necesariamente la misma relevancia aunque compartan strikes y OI." },
    { type: "paragraph", text: "GoodTrading excluye contratos expirados y usa timestamps para calcular el tiempo a expiración sobre una base de 365 días. Universos locales y broad pueden diferir. Esta lesson explica la dimensión temporal, no publica una fórmula propietaria para priorizar vencimientos." },
    { type: "list", items: ["Expiry identifica el reloj del contrato.", "DTE/TTE es derivado del timestamp actual.", "La cercanía temporal no es suficiente por sí sola.", "La cobertura de IV y OI limita la lectura."] },
    source("Expiry es observado en el instrumento; DTE y Expiry GEX son derivados. La prioridad táctica queda protegida para la capa MEMBER/Playbook."),
  ]),
  "gamma-and-dealer-hedging-16-why-gex-models-disagree": content([
    { type: "heading", level: 2, text: "No existe un GEX universal" },
    { type: "paragraph", text: "Dos modelos pueden discrepar sin que uno sea necesariamente un error. Pueden partir de snapshots distintos de OI, IV o spot; incluir expiries y strikes diferentes; aplicar otra normalización; o asignar signos diferentes a una misma observación." },
    { type: "list", items: ["Timestamp y frescura del snapshot.", "Cobertura y fuente de IV.", "Contrato y tamaño de contrato.", "Ventana de expiración y strike band.", "Spot utilizado para evaluar Gamma.", "Supuestos de lado dealer.", "Tratamiento de filas incompletas o fallback."] },
    { type: "paragraph", text: "La comparación correcta empieza por alinear procedencia, universo, unidades y fórmula. Un número más grande no es automáticamente más verdadero; una salida bootstrap tampoco debe presentarse como live." },
    source("GEX es un modelo reproducible solo si se documentan inputs, filtros, timestamp y convenciones. No es un dato observado único del mercado."),
  ]),
  "gamma-and-dealer-hedging-17-gamma-flip": content([
    { type: "heading", level: 2, text: "El nivel donde cambia el signo estimado" },
    { type: "paragraph", text: "Gamma Flip es el nivel del spot donde la curva de Net GEX estimada cambia de signo. GoodTrading evalúa la curva en distintos spots, busca cruces y puede interpolar entre dos puntos. Si hay varios cruces, la variante puede priorizar uno según su relación con el spot." },
    { type: "paragraph", text: "El producto distingue variantes local, global, broad y operational legacy. No deben mezclarse como si fueran el mismo número: pueden usar universos, expiries, snapshots y reglas de selección diferentes." },
    { type: "list", items: ["Es un nivel de transición del modelo.", "Puede no existir un cruce válido.", "Puede haber más de un cruce.", "No es una entrada automática ni soporte/resistencia garantizada."] },
    source("El flip es derivado de una curva GEX. El instrumento, OI, IV y spot son inputs; el cruce y su interpretación son modelados."),
  ]),
  "gamma-and-dealer-hedging-18-positive-gamma-regime": content([
    { type: "heading", level: 2, text: "Contexto positivo, no dirección" },
    { type: "paragraph", text: "Un régimen Positive Gamma indica que la exposición neta estimada tiene signo positivo bajo el universo y la convención elegidos. Puede ser consistente con una respuesta de cobertura más estabilizadora, pero la observación real debe confirmar si el precio pierde continuidad, encuentra liquidez o simplemente sigue una tendencia por otros motivos." },
    { type: "list", items: ["El régimen depende de datos y filtros.", "No significa que el precio deba caer.", "No garantiza mean reversion.", "No sustituye la lectura de ejecución, liquidez y noticias."] },
    { type: "paragraph", text: "Si el dato proviene de BOOTSTRAP, o si la fuente es NO_DATA con valores de recuperación, el estado no puede comunicarse como una lectura live válida." },
    source("Positive Gamma es un régimen derivado. La calidad depende de source, frescura y cobertura; no es un hecho direccional."),
  ]),
  "gamma-and-dealer-hedging-19-negative-gamma-regime": content([
    { type: "heading", level: 2, text: "Contexto negativo, no señal alcista" },
    { type: "paragraph", text: "Negative Gamma indica que la exposición neta estimada tiene signo negativo bajo el universo y convención seleccionados. Puede ser consistente con ajustes de cobertura más pro-cíclicos, pero la estructura no obliga a que el precio suba ni a que continúe una ruptura." },
    { type: "list", items: ["Negative Gamma no equivale a bullish.", "No garantiza tendencia ni breakout.", "La liquidez puede absorber o invalidar la hipótesis.", "El modelo no observa inventario real de dealers."] },
    { type: "paragraph", text: "La lectura debe combinarse con spot flow, futures, perpetuals, Order Flow, liquidez, volatilidad y eventos. Un régimen aislado no tiene suficiente información para una decisión ejecutable." },
    source("Negative Gamma es una clasificación derivada/modelada, no una orden ni una medición directa de cobertura dealer."),
  ]),
  "gamma-and-dealer-hedging-20-crossing-the-flip": content([
    { type: "heading", level: 2, text: "Cambiar de contexto no es aceptar un régimen" },
    { type: "paragraph", text: "Cuando el spot cruza el nivel estimado, cambia el contexto de la curva GEX según el modelo. Un tick por encima o por debajo no demuestra que el mercado haya establecido un nuevo régimen: el nivel puede moverse, el cruce puede ser local y la liquidez puede rechazar el desplazamiento." },
    { type: "paragraph", text: "Para hablar de aceptación o rechazo hacen falta comportamiento de subasta, ejecución, respuesta de liquidez y consistencia temporal. Course 09 presenta el problema; no publica el criterio operativo exacto." },
    { type: "list", items: ["Separa cruce matemático de aceptación de mercado.", "Distingue flip local, global y broad.", "Revisa fuente y timestamp antes de interpretar.", "No uses el cruce como entrada automática."] },
    source("El cruce es observado como movimiento de spot frente a un nivel derivado; aceptación/rechazo es una capa estructural protegida."),
  ]),
  "gamma-and-dealer-hedging-21-magnet-zones": content([
    { type: "heading", level: 2, text: "Zonas de atención estructural" },
    { type: "paragraph", text: "Gamma magnets son zonas derivadas a partir de concentración y relaciones estructurales del mapa de opciones. El contrato actual las describe como un RELATIVE_STRUCTURAL_SCORE: un puntaje relativo para ordenar contexto local, no una probabilidad calibrada." },
    { type: "paragraph", text: "Un magnet no es un target, no garantiza atracción y no implica que el precio deba visitarlo. Puede perder relevancia si cambia spot, OI, IV, expiry, liquidez o la fuente de datos." },
    { type: "list", items: ["Compara el magnet con spot y expiración.", "Observa si existe concentración suficiente.", "No conviertas score relativo en porcentaje.", "Contrasta la zona con respuesta real del precio."] },
    source("Magnet: derivado y estructural. No es una observación de órdenes futuras ni una probabilidad calibrada."),
  ]),
  "gamma-and-dealer-hedging-22-concentrated-gamma": content([
    { type: "heading", level: 2, text: "Concentración y sensibilidad" },
    { type: "paragraph", text: "La Gamma puede concentrarse alrededor de ciertos strikes o vencimientos. Esa concentración señala dónde el modelo estima una mayor sensibilidad agregada, especialmente cuando coinciden OI, IV y una relación relevante con el spot." },
    { type: "paragraph", text: "Concentración no garantiza pinning, reversión ni soporte. Una fila con gran OI puede tener IV ausente, vencimiento distante o una convención que no represente la posición real de todos los participantes. La zona necesita contexto." },
    { type: "list", items: ["Separa concentración de influencia observada.", "Revisa expiry y cobertura de IV.", "No sumes automáticamente instrumentos distintos.", "Busca confirmación en liquidez y ejecución."] },
    source("Concentrated Gamma es una agregación derivada. Strike y OI pueden ser observados, pero la importancia de la zona es una interpretación modelada."),
  ]),
  "gamma-and-dealer-hedging-23-expiration-effects": content([
    { type: "heading", level: 2, text: "Cuando cambia el reloj" },
    { type: "paragraph", text: "A medida que se acerca una expiración, cambia el tiempo restante y pueden cambiar Gamma, Charm, IV y la relevancia de una concentración de OI. Una opción que hoy domina un agregado puede perder peso o cambiar de sensibilidad a medida que el reloj avanza." },
    { type: "paragraph", text: "GoodTrading excluye contratos expirados, calcula el tiempo exacto con timestamps y usa una base de 365 días. La existencia de comportamiento corto no implica que exista un modo de producto 0DTE dedicado." },
    { type: "list", items: ["Expiry es parte de la identidad del contrato.", "DTE/TTE es un cálculo, no una estrategia.", "Charm puede modificar Delta con el paso del tiempo.", "OI e IV también pueden cambiar antes de la expiración."] },
    source("Expiry es dato del instrumento; cambios de Gamma, Charm y exposición son derivados. No se afirma soporte dedicado 0DTE."),
  ]),
  "gamma-and-dealer-hedging-24-vanna": content([
    { type: "heading", level: 2, text: "Vanna dentro de una exposición agregada" },
    { type: "paragraph", text: "Course 08 introdujo Vanna. Aquí interesa su papel en la cobertura: si cambia la volatilidad implícita, puede cambiar la Delta y por tanto el hedge requerido de una cartera. La contribución depende del contrato, spot, strike, IV y tiempo a expiración." },
    { type: "paragraph", text: "El engine actual calcula Vanna cuando dispone de spot, strike, expiry futura, OI positivo e IV válida. Luego agrega exposiciones y cobertura de filas. Esa salida es derivada y puede ser incompleta si solo una parte de la superficie tiene datos válidos." },
    { type: "list", items: ["Vanna no es un flujo observado.", "No asumas que una bias resume toda la cadena.", "La convención de signo importa.", "Ausencia de filas no equivale a exposición cero."] },
    source("Vanna es calculada. El hedge-flow asociado es un modelo; no representa transacciones Vanna observadas."),
  ]),
  "gamma-and-dealer-hedging-25-charm": content([
    { type: "heading", level: 2, text: "Charm y el paso del tiempo" },
    { type: "paragraph", text: "Charm describe una sensibilidad relacionada con cómo puede cambiar Delta cuando pasa el tiempo. En una cartera, esa evolución puede modificar las necesidades de cobertura incluso si el spot no realiza un gran movimiento." },
    { type: "paragraph", text: "El engine calcula Charm para filas válidas y lo expresa como exposición diaria. El resultado depende de la fórmula, expiry, IV, OI, spot y convención de signo. No debe presentarse como flujo temporal observado de dealers." },
    { type: "list", items: ["El calendario no es una orden de cobertura.", "La sensibilidad cambia con strike y vencimiento.", "Cobertura parcial puede ocultar parte del efecto.", "Charm no es una señal direccional independiente."] },
    source("Charm es una métrica derivada; su contribución a hedge pressure es modelada, no una ejecución observada."),
  ]),
  "gamma-and-dealer-hedging-26-dte": content([
    { type: "heading", level: 2, text: "Tiempo restante hasta expiry" },
    { type: "paragraph", text: "DTE es una forma práctica de hablar del tiempo hasta expiración. En el engine, el tiempo se calcula desde el timestamp exacto del contrato hasta el momento de evaluación, sobre una base de 365 días. Ese valor afecta Gamma, Vanna, Charm y otras sensibilidades." },
    { type: "paragraph", text: "DTE no es una regla para priorizar automáticamente una opción. Una expiración cercana puede tener poco OI o mala cobertura de IV; una lejana puede contener una concentración relevante. La interpretación necesita comparar tiempo, datos y spot." },
    { type: "list", items: ["Contratos expirados quedan fuera del cálculo live.", "La unidad temporal debe mantenerse explícita.", "DTE cambia continuamente.", "La prioridad táctica exacta queda protegida."] },
    source("Expiry y timestamp son inputs observados; DTE/TTE es derivado. La selección táctica de expiries no se publica en esta lesson."),
  ]),
  "gamma-and-dealer-hedging-27-iv-changes": content([
    { type: "heading", level: 2, text: "IV cambia la sensibilidad" },
    { type: "paragraph", text: "La volatilidad implícita participa en el cálculo de Gamma, Vanna y Charm. Si cambia la IV, también puede cambiar el valor estimado de esas sensibilidades aun cuando spot, strike y OI no se muevan." },
    { type: "paragraph", text: "Por eso una curva GEX no es estática. El engine intenta seleccionar IV mark, bid o ask según disponibilidad; si no existe una IV válida, la fila puede quedar fuera de la contribución. Una variación de IV no es por sí sola una señal de compra o venta." },
    { type: "list", items: ["IV recibida es input de mercado cuando está disponible.", "Gamma/GEX resultante es derivado.", "Bid, ask y mark pueden producir valores diferentes.", "La cobertura de IV debe acompañar cualquier interpretación."] },
    source("IV puede ser recibida desde la venue; el efecto sobre Greeks y hedge pressure es calculado por el modelo."),
  ]),
  "gamma-and-dealer-hedging-28-expiry-decay": content([
    { type: "heading", level: 2, text: "La superficie cambia con el calendario" },
    { type: "paragraph", text: "Expiry decay combina varios procesos: pasa el tiempo, cambia el tiempo a vencimiento, pueden cambiar Gamma y Charm, y también pueden modificarse OI, IV, spot y liquidez. No es correcto reducir todo a una resta diaria fija." },
    { type: "list", items: ["Calendar decay: queda menos vida contractual.", "Gamma concentration: la sensibilidad puede redistribuirse.", "Charm: Delta puede cambiar con el tiempo.", "OI/IV: la superficie puede cambiar por actividad de mercado.", "Expiración: contratos vencidos dejan de ser elegibles."] },
    { type: "paragraph", text: "La lectura debe comparar snapshots con timestamps y conservar la diferencia entre cambio observado en inputs y efecto derivado en exposición. No se publican umbrales operativos ni criterios de ejecución." },
    source("El paso del tiempo y los cambios de OI/IV son inputs o estados observables; decay y sus efectos sobre hedge son derivados/modelados."),
  ]),
};
