import type { AcademyContentBlock } from "@/academy/catalog";

export const MARKET_MECHANICS_CONTENT: Record<string, AcademyContentBlock[]> = {
  "market-mechanics-01-what-is-a-market": [
    { type: "heading", level: 2, text: "Un mercado es un mecanismo de encuentro" },
    { type: "paragraph", text: "Un mercado es la interacción continua entre compradores y vendedores que expresan precios y cantidades. El venue o exchange recibe esas órdenes, las organiza y las cruza cuando las condiciones son compatibles." },
    { type: "heading", level: 3, text: "Cómo se forma el precio" },
    { type: "paragraph", text: "Las ofertas de compra se sitúan por debajo del mercado y las ofertas de venta por encima. Cuando una orden ejecutable encuentra una contraparte, ocurre una transacción. La sucesión de esas transacciones forma la serie de precios que luego observamos." },
    { type: "paragraph", text: "El gráfico es una representación de lo que ocurrió: resume operaciones en velas, volumen y otros campos. No es el mecanismo de matching ni muestra por sí solo todas las órdenes que esperaban ser ejecutadas." },
    { type: "callout", title: "Modelo mental", text: "El gráfico muestra el resultado de la subasta; el libro y las ejecuciones ayudan a estudiar el proceso que produjo ese resultado." },
  ],
  "market-mechanics-02-buyers-and-sellers": [
    { type: "heading", level: 2, text: "Cada operación tiene dos lados" },
    { type: "paragraph", text: "Toda operación ejecutada tiene un comprador y un vendedor. Si una transacción ocurre por 100 unidades, ambas partes intercambian la misma cantidad. Por eso la frase «hay más compradores que vendedores» es imprecisa cuando se habla de operaciones ya ejecutadas." },
    { type: "heading", level: 3, text: "Quién cruza el spread" },
    { type: "paragraph", text: "La diferencia relevante es quién acepta cruzar la cotización disponible. Un comprador agresivo puede ejecutar contra el Ask; un vendedor agresivo puede ejecutar contra el Bid. La contraparte puede estar esperando pasivamente en ese nivel." },
    { type: "list", items: ["Comprador y vendedor siempre existen en una ejecución.", "Agresor describe la urgencia de cruzar liquidez, no una identidad permanente.", "La agresión se observa mediante datos de ejecución y contexto, no mediante una suposición sobre la intención privada."] },
    { type: "callout", title: "Corrección importante", text: "La pregunta útil no es quién existe en mayor número, sino quién está aceptando el precio disponible y cómo responde el mercado." },
  ],
  "market-mechanics-03-bid-and-ask": [
    { type: "heading", level: 2, text: "La cotización de dos lados" },
    { type: "paragraph", text: "El mejor Bid es el precio más alto visible al que alguien está dispuesto a comprar. El mejor Ask es el precio más bajo visible al que alguien está dispuesto a vender. Juntos forman la cotización vigente del mercado." },
    { type: "heading", level: 3, text: "Ejemplo" },
    { type: "list", items: ["Best Bid: 99.", "Best Ask: 100.", "Un comprador que cruza puede ejecutar a 100, el Ask.", "Un vendedor que cruza puede ejecutar a 99, el Bid."] },
    { type: "paragraph", text: "El Last es el precio de la última operación, no necesariamente el Bid ni el Ask actuales. Las cotizaciones pueden cambiar antes de la siguiente operación y una orden visible no garantiza que permanezca disponible." },
    { type: "callout", title: "Distinción", text: "Bid y Ask describen precios cotizados y potencialmente ejecutables; Last describe una transacción que ya ocurrió." },
  ],
  "market-mechanics-04-spread": [
    { type: "heading", level: 2, text: "La distancia entre compra y venta" },
    { type: "paragraph", text: "El spread es la diferencia entre el mejor Ask y el mejor Bid. Si el Bid es 99 y el Ask es 100, el spread es 1. Es la separación mínima entre ambos lados de la cotización." },
    { type: "heading", level: 3, text: "Qué puede indicar" },
    { type: "paragraph", text: "Un spread estrecho suele acompañar una cotización con menor fricción inmediata; uno amplio puede reflejar menor liquidez disponible, mayor incertidumbre o un momento de transición. Esa relación no convierte al spread en una señal direccional automática." },
    { type: "list", items: ["El spread cambia cuando se agregan, ejecutan o cancelan órdenes.", "Cruzar el spread tiene un coste implícito para quien busca ejecución inmediata.", "Un spread amplio no dice por sí solo si el precio subirá o bajará."] },
    { type: "callout", title: "Lectura correcta", text: "El spread informa sobre la fricción de la cotización, no sobre la dirección futura del mercado." },
  ],
  "market-mechanics-05-liquidity": [
    { type: "heading", level: 2, text: "La capacidad de negociar" },
    { type: "paragraph", text: "Liquidez es la capacidad de comprar o vender sin mover excesivamente el precio. Depende de cuánta cantidad está disponible, a qué distancia de la cotización y durante cuánto tiempo permanece allí." },
    { type: "heading", level: 3, text: "Liquidez disponible y profundidad" },
    { type: "paragraph", text: "La liquidez resting son órdenes que esperan en niveles concretos. La profundidad describe cómo se distribuye esa cantidad alrededor del precio. El volumen, en cambio, mide cuánto se negoció; una cosa puede ser alta aunque la otra no lo sea." },
    { type: "list", items: ["Liquidez no es sinónimo de volumen.", "La liquidez visible puede cambiar o cancelarse.", "Una orden grande no es automáticamente soporte o resistencia.", "El impacto depende del tamaño de la orden frente a la cantidad disponible."] },
    { type: "callout", title: "Cuidado", text: "Una pared visible es información sobre una orden en espera, no una garantía de defensa del precio." },
  ],
  "market-mechanics-06-order-book": [
    { type: "heading", level: 2, text: "El libro de órdenes" },
    { type: "paragraph", text: "El Order Book organiza las órdenes limit que esperan ejecución por nivel de precio. Normalmente muestra bids por debajo del mercado y asks por encima, con la cantidad disponible en cada nivel." },
    { type: "heading", level: 3, text: "Un estado dinámico" },
    { type: "list", items: ["Se agregan nuevas órdenes.", "Las operaciones ejecutan parte o toda la cantidad.", "Las órdenes pueden cancelarse antes de ejecutar.", "Los niveles y cantidades cambian mientras observas."] },
    { type: "paragraph", text: "El libro es una fotografía cambiante de liquidez visible, no un contrato de ejecución futura. Para interpretarlo con profundidad se necesitan datos de profundidad y su evolución temporal; esa lectura pertenece después a DOM & Liquidity y Heatmap & Bookmap." },
    { type: "callout", title: "Principio", text: "Lo que aparece en el libro puede desaparecer, ejecutarse o modificarse antes de que el precio llegue a ese nivel." },
  ],
  "market-mechanics-07-limit-orders": [
    { type: "heading", level: 2, text: "Una orden con restricción de precio" },
    { type: "paragraph", text: "Una orden Limit especifica el precio máximo que aceptarás al comprar o el mínimo que aceptarás al vender. Si no encuentra una contraparte compatible, puede permanecer esperando en el libro." },
    { type: "heading", level: 3, text: "Cola y ejecución" },
    { type: "paragraph", text: "Cuando varias órdenes esperan en el mismo nivel, normalmente existe una cola de prioridad definida por el venue. Llegar primero puede importar, pero la prioridad exacta depende de las reglas del mercado. Una Limit no garantiza que se ejecute." },
    { type: "list", items: ["Controla mejor el precio que una orden Market.", "Puede no ejecutarse o ejecutarse parcialmente.", "Mientras espera, aporta liquidez visible al libro.", "Si se coloca de forma marketable, puede ejecutar inmediatamente y comportarse como una orden que cruza."] },
    { type: "callout", title: "No prometer", text: "Ver una orden Limit en un nivel no permite prometer un fill ni asumir que permanecerá allí." },
  ],
  "market-mechanics-08-market-orders": [
    { type: "heading", level: 2, text: "Priorizar ejecución sobre precio exacto" },
    { type: "paragraph", text: "Una orden Market expresa la intención de ejecutar contra la liquidez disponible ahora. No fija un precio único: acepta los precios ofrecidos por el libro en el momento en que llega al mercado." },
    { type: "heading", level: 3, text: "Consumo y slippage" },
    { type: "paragraph", text: "Si hay 2 unidades disponibles en el Ask a 100 y una orden Market necesita 5, puede ejecutar 2 a 100 y buscar las 3 restantes en el siguiente nivel, por ejemplo 101. El precio promedio resultante puede ser peor que el primer precio observado; esa diferencia es slippage." },
    { type: "list", items: ["Busca inmediatez, no un precio garantizado.", "Puede consumir varios niveles si el tamaño supera la liquidez disponible.", "El tipo Market no es alcista ni bajista por sí mismo; importa quién la cruza y la respuesta posterior.", "La profundidad y la velocidad de cambio condicionan el resultado."] },
    { type: "callout", title: "Mecánica", text: "Market describe cómo se busca ejecutar, no la dirección que tendrá el precio después." },
  ],
  "market-mechanics-09-liquidity-makers": [
    { type: "heading", level: 2, text: "Proporcionar liquidez" },
    { type: "paragraph", text: "Un Liquidity Maker coloca una orden que espera ser ejecutada por alguien que cruza hacia ella. En ese sentido, aporta liquidez al libro y permite que otro participante encuentre una contraparte disponible." },
    { type: "paragraph", text: "Pasivo describe la posición de la orden frente al flujo actual, no la fortaleza o intención del participante. Una orden pasiva puede permanecer, ser ejecutada, cancelarse o modificarse. Tampoco toda Limit es pasiva durante toda su vida: si cruza una cotización, puede ejecutar de inmediato." },
    { type: "list", items: ["Aporta una cotización esperando contraparte.", "Puede recibir prioridad según la cola del nivel.", "Las comisiones maker/taker dependen del venue y sus reglas.", "Proporcionar liquidez no garantiza que el precio sea defendido."] },
    { type: "callout", title: "Precisión", text: "Maker/taker describe la relación de la orden con la liquidez del venue; no clasifica a una persona como siempre pasiva o siempre agresiva." },
  ],
  "market-mechanics-10-liquidity-takers": [
    { type: "heading", level: 2, text: "Tomar liquidez disponible" },
    { type: "paragraph", text: "Un Liquidity Taker cruza la cotización para ejecutar contra órdenes que ya esperan. Una orden Market suele hacerlo, pero una Limit con precio suficientemente agresivo también puede ser marketable y ejecutar de inmediato." },
    { type: "heading", level: 3, text: "Maker frente a taker" },
    { type: "list", items: ["Maker: deja una orden que puede esperar en el libro.", "Taker: consume una orden visible para obtener ejecución.", "Maker/taker depende del resultado de la orden, no solo del nombre Market o Limit.", "El taker acepta la liquidez y el precio disponibles en ese instante."] },
    { type: "paragraph", text: "Tomar liquidez puede reducir la cantidad visible en un nivel y contribuir a que la siguiente ejecución ocurra más lejos. Eso describe una mecánica; no garantiza continuidad de precio." },
    { type: "callout", title: "Resumen", text: "Taker significa cruzar y consumir liquidez; la dirección y la consecuencia posterior requieren observar más datos." },
  ],
  "market-mechanics-11-aggressive-participation": [
    { type: "heading", level: 2, text: "Urgencia para ejecutar" },
    { type: "paragraph", text: "La participación agresiva aparece cuando una orden cruza el spread: un comprador levanta el Ask o un vendedor golpea el Bid. La operación obtiene prioridad de ejecución a cambio de aceptar la liquidez disponible." },
    { type: "heading", level: 3, text: "Efecto inmediato" },
    { type: "paragraph", text: "El agresor reduce la cantidad disponible en el lado que consume. Si hay poca cantidad y llegan más órdenes en la misma dirección, las ejecuciones pueden avanzar por niveles. Si aparece liquidez suficiente o la agresión se detiene, el resultado puede ser distinto." },
    { type: "list", items: ["Agresión implica urgencia, no certeza.", "Un comprador agresivo no garantiza continuación alcista.", "Un vendedor agresivo no garantiza continuación bajista.", "La respuesta del precio es tan importante como la agresión observada."] },
    { type: "callout", title: "Preparación", text: "La agresión es una parte del proceso de subasta. Los cursos de Order Flow estudiarán cómo medirla y contextualizarla." },
  ],
  "market-mechanics-12-passive-participation": [
    { type: "heading", level: 2, text: "Liquidez que espera" },
    { type: "paragraph", text: "La participación pasiva se expresa mediante órdenes resting que esperan que otra orden llegue a su precio. Puede ofrecer liquidez, absorber operaciones durante un tiempo o terminar siendo consumida." },
    { type: "heading", level: 3, text: "No confundir pasividad con debilidad" },
    { type: "paragraph", text: "Una orden pasiva puede frenar temporalmente el avance si aporta cantidad suficiente, pero también puede ser ejecutada por completo. La reposición —agregar nueva cantidad después de ejecuciones— es un concepto útil, aunque observarla correctamente requiere datos más detallados." },
    { type: "list", items: ["La liquidez puede permanecer, cambiar o cancelarse.", "Pasivo describe cómo entra la orden al proceso, no su resultado final.", "La absorción es una interpretación que exige relacionar ejecuciones, precio y liquidez."] },
    { type: "callout", title: "Criterio", text: "Solo después de observar la respuesta del precio puedes evaluar qué ocurrió con la liquidez pasiva; no la conviertas en una defensa garantizada." },
  ],
  "market-mechanics-13-why-price-actually-moves": [
    { type: "heading", level: 2, text: "El precio cambia entre niveles disponibles" },
    { type: "paragraph", text: "El precio cambia cuando la liquidez ejecutable de un nivel ya no alcanza para las órdenes que buscan cruzar, o cuando esa liquidez se cancela y deja otro nivel como referencia disponible. Las operaciones siguientes ocurren entonces a precios distintos." },
    { type: "heading", level: 3, text: "Varios procesos pueden combinarse" },
    { type: "list", items: ["Flujo agresivo consume cantidades visibles.", "La liquidez disponible se agota o se desplaza.", "Órdenes resting se cancelan antes de ser ejecutadas.", "Nuevas órdenes modifican la cotización y la profundidad.", "El mercado reprecifica mientras busca nuevas contrapartes."] },
    { type: "paragraph", text: "Por eso «el precio sube porque hay más compradores que vendedores» simplifica demasiado. En cada trade hay ambos lados; lo observable es la interacción entre órdenes agresivas, liquidez y respuesta del precio." },
    { type: "callout", title: "Causa mecánica", text: "El precio se mueve hacia donde encuentra la próxima liquidez ejecutable; la dirección no se explica contando compradores y vendedores de forma abstracta." },
  ],
  "market-mechanics-14-liquidity-consumption": [
    { type: "heading", level: 2, text: "Agotar cantidad en un nivel" },
    { type: "paragraph", text: "Liquidity consumption ocurre cuando operaciones agresivas ejecutan contra órdenes resting y reducen la cantidad disponible. Si un nivel queda agotado, la siguiente operación compatible puede encontrar liquidez en otro precio." },
    { type: "heading", level: 3, text: "Consumo no es cancelación" },
    { type: "list", items: ["Consumo: la cantidad desaparece porque fue ejecutada.", "Cancelación: la orden se retira sin ejecutar.", "Ambos pueden reducir la liquidez visible.", "Sin el dato apropiado, no siempre puedes saber cuál proceso ocurrió."] },
    { type: "paragraph", text: "Ejemplo: si el Ask 100 tiene 2 unidades y llegan 5 unidades compradoras, las primeras 2 pueden ejecutarse allí y las restantes buscar 101. El recorrido exacto depende de la profundidad real disponible." },
    { type: "callout", title: "Observación", text: "Mira la evolución de cantidad, ejecuciones y precio. No atribuyas automáticamente una desaparición a consumo o a cancelación." },
  ],
  "market-mechanics-15-auction-process": [
    { type: "heading", level: 2, text: "El mercado como subasta continua" },
    { type: "paragraph", text: "Una subasta busca encontrar precios donde compradores y vendedores estén dispuestos a negociar. El mercado explora niveles, encuentra contrapartes y actualiza el precio según la liquidez y la urgencia disponible." },
    { type: "heading", level: 3, text: "Balance y movimiento" },
    { type: "paragraph", text: "Cuando existe negociación suficiente alrededor de una zona, el precio puede permanecer en balance. Cuando cambia la disposición a cruzar o la liquidez disponible, la subasta puede desplazarse hacia nuevos precios en busca de intercambio." },
    { type: "list", items: ["Exploración: el precio visita una zona para buscar negocio.", "Trade: compradores y vendedores ejecutan.", "Balance: se concentra actividad alrededor de un área.", "Desplazamiento: la subasta busca otro nivel de acuerdo."] },
    { type: "callout", title: "Marco mental", text: "Precio, liquidez y ejecución son partes de una subasta; una vela aislada es solo una de sus representaciones." },
  ],
  "market-mechanics-16-acceptance": [
    { type: "heading", level: 2, text: "Cuando una zona nueva encuentra negocio" },
    { type: "paragraph", text: "Hablamos de aceptación cuando el mercado no solo visita un área nueva, sino que permanece allí y ejecuta operaciones alrededor de esos precios. El tiempo, la actividad y la continuidad ayudan a diferenciar una visita breve de un área donde se está haciendo negocio." },
    { type: "heading", level: 3, text: "No es una sola vela" },
    { type: "paragraph", text: "Una vela que cierra más arriba no prueba aceptación por sí sola. Hay que observar si el precio puede mantenerse, si aparece actividad y si la subasta continúa encontrando contrapartes en la nueva zona." },
    { type: "list", items: ["Considera ubicación y timeframe.", "Observa permanencia y ejecuciones, no solo color de vela.", "Distingue aceptación de una exploración rápida.", "No conviertas aceptación en señal automática de entrada."] },
    { type: "callout", title: "Contexto", text: "Aceptación describe comportamiento de la subasta alrededor de una zona; no prescribe una operación." },
  ],
  "market-mechanics-17-rejection": [
    { type: "heading", level: 2, text: "Explorar sin sostener negocio" },
    { type: "paragraph", text: "Hay rechazo cuando el precio explora un área pero no consigue sostener suficiente negocio allí y vuelve hacia una zona previa. La idea se refiere a la relación entre exploración, ejecución y retorno, no a una vela con una forma específica." },
    { type: "heading", level: 3, text: "Qué observar" },
    { type: "list", items: ["El precio visita el área.", "La actividad no se sostiene o la liquidez cambia.", "La subasta vuelve hacia precios anteriores.", "El resultado debe leerse dentro del contexto más amplio."] },
    { type: "paragraph", text: "Una mecha larga puede ser compatible con rechazo, pero no lo demuestra por sí misma. El mismo patrón visual puede aparecer por motivos distintos. Esta lectura no es un trigger ni una regla de ejecución." },
    { type: "callout", title: "Cuidado", text: "Rechazo es una descripción contextual del comportamiento del precio, no una orden de vender o comprar." },
  ],
  "market-mechanics-18-imbalance": [
    { type: "heading", level: 2, text: "Desequilibrio temporal de presión" },
    { type: "paragraph", text: "En sentido mecánico, un imbalance aparece cuando la demanda agresiva inmediata no encuentra una cantidad equivalente de liquidez opuesta disponible en ese rango. Esa diferencia puede ejercer presión y provocar una repricing hacia otros niveles." },
    { type: "paragraph", text: "El desequilibrio es dinámico: puede desaparecer si llega liquidez, si se cancela la agresión o si las operaciones encuentran nuevas contrapartes. No equivale automáticamente a una tendencia ni a continuación." },
    { type: "list", items: ["Relaciona agresión con liquidez disponible.", "Observa la respuesta del precio.", "Distingue presión momentánea de aceptación sostenida.", "No infieras intención privada con certeza a partir de un solo dato."] },
    { type: "callout", title: "Distinción", text: "Aquí hablamos de imbalance de mercado como concepto. Las reglas de imbalances en Footprint se estudian después en Footprint Mastery." },
  ],
  "market-mechanics-19-who-controls-the-auction": [
    { type: "heading", level: 2, text: "Observar control, no adivinar intención" },
    { type: "paragraph", text: "En esta actividad no buscas etiquetar una vela como alcista o bajista. Observa la relación entre agresión, liquidez y respuesta del precio para evaluar qué lado está logrando más progreso en la subasta." },
    { type: "heading", level: 3, text: "Preguntas para el análisis" },
    { type: "list", items: ["¿La compra agresiva produce progreso hacia precios superiores?", "¿La venta agresiva produce progreso hacia precios inferiores?", "¿El mercado está aceptando territorio nuevo o vuelve al área anterior?", "¿Un lado muestra agresión pero no consigue avanzar?", "¿La actividad está balanceada alrededor de una zona?"] },
    { type: "paragraph", text: "El control es una inferencia basada en la relación entre lo que se ejecuta, la liquidez disponible y la reacción posterior del precio. No se demuestra mirando solamente el color de una vela ni atribuyendo una intención institucional que los datos no pueden confirmar." },
    { type: "callout", title: "Lab", text: "El ejercicio mantiene formato QUIZ sobre el gráfico. No ejecuta operaciones ni implementa un replay de mercado en esta versión." },
  ],
};
