import type { AcademyContentBlock } from "@/academy/catalog";

export const OPTIONS_FOUNDATIONS_CONTENT: Record<string, AcademyContentBlock[]> = {
  "options-foundations-01-what-is-an-option": [
    { type: "heading", level: 2, text: "Un contrato derivado" },
    { type: "paragraph", text: "Una opción es un contrato cuyo valor depende de un activo subyacente, como BTC o ETH. Da al comprador un derecho bajo ciertas condiciones, mientras que el vendedor o writer asume una obligación contractual si el comprador ejerce." },
    { type: "paragraph", text: "Las dos formas básicas son Call y Put. Cada contrato define un strike, una expiración y una prima. La opción tiene vida finita: su valor y sus sensibilidades cambian mientras se acerca el vencimiento." },
    { type: "list", items: ["El comprador paga la prima y obtiene un derecho.", "El vendedor recibe la prima y asume obligaciones según el contrato.", "El subyacente, el tiempo y la volatilidad influyen en la valoración.", "Un contrato de opción no es una predicción automática de dirección."] },
    { type: "callout", title: "Base", text: "Antes de preguntar si una opción es alcista o bajista, identifica qué contrato existe y qué exposición representa." },
  ],
  "options-foundations-02-call": [
    { type: "heading", level: 2, text: "Derecho a comprar" },
    { type: "paragraph", text: "Una Call otorga al comprador el derecho, no la obligación, de comprar el subyacente al strike bajo las condiciones del contrato antes o en su expiración. El comprador paga una prima por ese derecho; el writer recibe la prima y asume la obligación correspondiente." },
    { type: "paragraph", text: "Con BTC en 70.000, una Call con strike 75.000 puede ganar valor si el subyacente sube, pero el resultado depende también de prima, tiempo y volatilidad. La definición del contrato no es igual a una recomendación de compra." },
    { type: "callout", title: "No inferir de OI", text: "Una Call abierta puede pertenecer a un comprador o a un vendedor. El Open Interest por sí solo no demuestra posicionamiento bullish." },
  ],
  "options-foundations-03-put": [
    { type: "heading", level: 2, text: "Derecho a vender" },
    { type: "paragraph", text: "Una Put otorga al comprador el derecho, no la obligación, de vender el subyacente al strike bajo las condiciones del contrato. El comprador paga una prima y el writer recibe esa prima a cambio de asumir una obligación potencial." },
    { type: "paragraph", text: "Una Put puede utilizarse para proteger una exposición, expresar una hipótesis o estructurar un riesgo. Por eso observar Put Open Interest no permite concluir automáticamente que el mercado sea bearish." },
    { type: "list", items: ["El strike define el precio contractual de referencia.", "La expiración limita la vida del derecho.", "El valor depende del subyacente y de variables de mercado.", "La posición real requiere conocer el lado del contrato, no solo su existencia."] },
    { type: "callout", title: "Precisión", text: "Put describe el tipo de contrato; no revela por sí sola quién tiene qué exposición." },
  ],
  "options-foundations-04-strike": [
    { type: "heading", level: 2, text: "El precio contractual de referencia" },
    { type: "paragraph", text: "El strike es el precio establecido en el contrato para el derecho de comprar o vender. En una cadena de opciones, los strikes organizan la superficie alrededor del precio actual del subyacente." },
    { type: "list", items: ["ITM: el contrato tiene valor intrínseco bajo la convención correspondiente.", "ATM: el strike está cerca del precio actual.", "OTM: todavía no tiene valor intrínseco bajo esa referencia.", "La clasificación cambia si cambia el precio del subyacente."] },
    { type: "paragraph", text: "Un strike no es automáticamente un soporte, resistencia o nivel de Gamma. Es primero una característica contractual. Las interpretaciones de posicionamiento requieren datos adicionales y supuestos explícitos." },
    { type: "callout", title: "Organización", text: "El strike permite ordenar contratos; no convierte una fila de la cadena en una señal operativa." },
  ],
  "options-foundations-05-expiration": [
    { type: "heading", level: 2, text: "Una vida finita" },
    { type: "paragraph", text: "Toda opción tiene una fecha y hora de expiración. El tiempo restante suele expresarse como DTE, days to expiration, y afecta cuánto tiempo queda para que cambien el subyacente, la volatilidad y el valor del contrato." },
    { type: "paragraph", text: "Una opción de corto vencimiento y otra con la misma estructura pero más tiempo no reaccionan igual. Las sensibilidades evolucionan y pueden volverse más pronunciadas cerca de la expiración, dependiendo del strike y de las condiciones del mercado." },
    { type: "list", items: ["Las expiraciones múltiples conviven en una cadena.", "DTE no es una estrategia; es una medida de tiempo restante.", "El paso del tiempo modifica las sensibilidades.", "No todas las opciones con el mismo strike tienen el mismo comportamiento si vencen en fechas distintas."] },
    { type: "callout", title: "Límite", text: "Conocer la fecha de vencimiento no permite anticipar por sí solo la dirección ni el resultado de una opción." },
  ],
  "options-foundations-06-premium": [
    { type: "heading", level: 2, text: "El precio de la opción" },
    { type: "paragraph", text: "La prima es el precio que paga el comprador y recibe el vendedor de la opción. Puede contener valor intrínseco —el valor inmediato bajo el contrato— y valor temporal, que refleja la posibilidad de cambios antes de la expiración." },
    { type: "paragraph", text: "La prima no depende únicamente de si el subyacente sube o baja. También intervienen el strike, el tiempo restante, la volatilidad implícita, la liquidez y las condiciones de mercado." },
    { type: "list", items: ["Valor intrínseco: relación actual entre subyacente y strike.", "Valor temporal: incertidumbre y oportunidad antes del vencimiento.", "Volatilidad implícita: expectativa incorporada en el precio, no una garantía.", "La prima puede cambiar aunque el spot permanezca casi estable."] },
    { type: "callout", title: "Idea clave", text: "Una opción tiene un precio propio. No es simplemente el precio del subyacente con una etiqueta distinta." },
  ],
  "options-foundations-07-delta": [
    { type: "heading", level: 2, text: "Sensibilidad local al subyacente" },
    { type: "paragraph", text: "Delta describe aproximadamente cuánto cambia el valor de una opción ante un pequeño cambio en el subyacente, manteniendo otras variables controladas. Es una sensibilidad de primer orden, no un resultado garantizado." },
    { type: "paragraph", text: "Bajo convenciones estándar, una Call tiene Delta positiva y una Put Delta negativa. El valor cambia con strike, tiempo, volatilidad y precio; por eso Delta tampoco es constante." },
    { type: "list", items: ["Una Delta cercana a 0,40 puede usarse como aproximación local.", "No significa que exista una probabilidad segura del 40%.", "La relación se deteriora si el movimiento es grande o cambian otras variables.", "Las carteras agregan Deltas de muchos contratos y vencimientos."] },
    { type: "callout", title: "Precisión", text: "Delta es una sensibilidad modelada. Las interpretaciones probabilísticas son aproximadas y dependen del modelo, no son certezas." },
  ],
  "options-foundations-08-gamma": [
    { type: "heading", level: 2, text: "La sensibilidad de Delta" },
    { type: "paragraph", text: "Gamma describe cuánto puede cambiar Delta cuando cambia el subyacente. Una Gamma más alta implica que Delta puede variar más rápidamente ante un movimiento determinado, especialmente en ciertas relaciones entre strike, tiempo y volatilidad." },
    { type: "paragraph", text: "Por ejemplo, una Call con Delta aproximada de 0,40 puede pasar a otra sensibilidad después de que BTC se mueva. Gamma ayuda a explicar por qué una cobertura basada en Delta necesita actualizarse." },
    { type: "list", items: ["Gamma no indica por sí sola dirección.", "Gamma no obliga al precio a ir hacia o alejarse de un strike.", "Depende de la estructura del contrato y del modelo.", "El impacto agregado requiere conocer posiciones, tamaño y cobertura."] },
    { type: "callout", title: "Fundamento", text: "Gamma explica cómo cambia una sensibilidad; no es una señal de trading ni una predicción automática del precio." },
  ],
  "options-foundations-09-theta": [
    { type: "heading", level: 2, text: "Sensibilidad al paso del tiempo" },
    { type: "paragraph", text: "Theta describe cómo puede cambiar el valor de una opción cuando pasa el tiempo, manteniendo conceptualmente constantes otras variables. A menudo se habla de time decay porque la vida restante se reduce." },
    { type: "paragraph", text: "La evolución no es necesariamente lineal ni igual cada día. Strike, volatilidad, distancia al spot y proximidad a la expiración modifican la sensibilidad." },
    { type: "list", items: ["Menos tiempo puede reducir el valor temporal.", "El efecto puede acelerarse cerca de la expiración.", "Un cambio de volatilidad o spot puede dominar el efecto del tiempo.", "Theta no es una tarifa diaria fija y garantizada."] },
    { type: "callout", title: "Cuidado", text: "Time decay es una sensibilidad del modelo, no una resta constante independiente del resto del mercado." },
  ],
  "options-foundations-10-vega": [
    { type: "heading", level: 2, text: "Sensibilidad a la volatilidad implícita" },
    { type: "paragraph", text: "Vega describe la sensibilidad aproximada del valor de una opción ante cambios en la volatilidad implícita, manteniendo conceptualmente controladas otras variables. Una variación de IV puede cambiar la prima aunque el spot se mueva poco." },
    { type: "paragraph", text: "Volatilidad implícita es la variable de volatilidad que el precio de la opción incorpora bajo un modelo. No es lo mismo que la volatilidad realizada, que describe cuánto se movió efectivamente el subyacente." },
    { type: "list", items: ["Vega no es la volatilidad.", "La sensibilidad cambia con strike y tiempo restante.", "Una subida de IV no garantiza la misma reacción en todos los contratos.", "La prima depende simultáneamente de spot, tiempo, IV y liquidez."] },
    { type: "callout", title: "Distinción", text: "Vega mide exposición al cambio de IV; no predice cuánto se moverá BTC o ETH." },
  ],
  "options-foundations-11-vanna": [
    { type: "heading", level: 2, text: "Una sensibilidad cruzada" },
    { type: "paragraph", text: "Vanna se usa para describir una sensibilidad cruzada que relaciona Delta y volatilidad. A nivel introductorio, ayuda a entender que un cambio de IV puede modificar la Delta de una opción y, por tanto, sus necesidades de cobertura." },
    { type: "paragraph", text: "La magnitud y el signo dependen de la convención, del modelo y del contrato. En una cartera, las contribuciones de muchas opciones pueden compensarse o reforzarse." },
    { type: "callout", title: "Preparación", text: "Vanna será relevante para estudiar coberturas agregadas más adelante, pero este concepto no define una señal ni un flujo direccional por sí solo." },
  ],
  "options-foundations-12-charm": [
    { type: "heading", level: 2, text: "Cómo evoluciona Delta con el tiempo" },
    { type: "paragraph", text: "Charm describe, bajo una convención de cálculo, cómo puede cambiar Delta a medida que pasa el tiempo mientras se mantienen conceptualmente controladas otras variables. Es otra razón por la que una cobertura de Delta puede necesitar ajustes incluso sin un gran movimiento del spot." },
    { type: "paragraph", text: "El efecto depende del contrato, del tiempo a expiración, del strike y del modelo. Puede ser especialmente relevante al aproximarse el vencimiento, pero no debe transformarse en una predicción direccional." },
    { type: "callout", title: "Límite", text: "Charm ayuda a describir la evolución temporal de una sensibilidad; no es una señal para comprar o vender." },
  ],
  "options-foundations-13-open-interest": [
    { type: "heading", level: 2, text: "Contratos que siguen abiertos" },
    { type: "paragraph", text: "Open Interest es el número de contratos de opciones que permanecen abiertos. Se organiza por strike y expiración y representa posiciones aún vigentes, no el volumen negociado durante un periodo." },
    { type: "heading", level: 3, text: "OI frente a volumen" },
    { type: "list", items: ["Volumen: contratos negociados durante un intervalo.", "Open Interest: contratos abiertos al finalizar o actualizarse el estado.", "Un aumento de OI puede relacionarse con apertura de posiciones, pero su interpretación exacta requiere el contexto de las operaciones.", "La distribución por strike y expiración muestra dónde están los contratos, no quién tiene cada lado."] },
    { type: "callout", title: "Regla de lectura", text: "OI por sí solo no identifica comprador, vendedor, lado long o short, dealer ni cobertura. Es una observación estructural, no una verdad direccional." },
  ],
  "options-foundations-14-dealer": [
    { type: "heading", level: 2, text: "Una categoría de participante y riesgo" },
    { type: "paragraph", text: "Dealer suele referirse a un participante que facilita transacciones, mantiene inventario o administra riesgo frente a posiciones de clientes y mercado. Puede actuar como contraparte o proveedor de liquidez, pero la estructura real contiene múltiples participantes y modelos de negocio." },
    { type: "paragraph", text: "En análisis de opciones, dealer también puede ser una categoría de modelado. Para inferir su exposición se necesitan supuestos sobre el lado de las posiciones, la cobertura y los datos disponibles." },
    { type: "list", items: ["No todos los dealers se comportan igual.", "No toda liquidez visible pertenece al mismo tipo de participante.", "Una etiqueta de dealer no revela por sí sola una intención.", "La exposición agregada depende de los contratos y supuestos incluidos."] },
    { type: "callout", title: "Precisión", text: "Dealer es una descripción funcional o de modelado, no una identidad única que pueda inferirse completamente desde OI." },
  ],
  "options-foundations-15-market-maker": [
    { type: "heading", level: 2, text: "Cotizar y gestionar inventario" },
    { type: "paragraph", text: "Un market maker publica Bid y Ask para facilitar liquidez y buscar compensación entre compras y ventas. Al hacerlo puede acumular inventario y exposición a precio, volatilidad, tiempo y otros riesgos." },
    { type: "paragraph", text: "La actividad de market making y el término dealer se solapan en algunos contextos, pero no son sinónimos perfectos. Market maker describe una actividad de cotización; dealer puede abarcar también funciones de contraparte y gestión de inventario." },
    { type: "list", items: ["La cotización ayuda a formar un mercado bilateral.", "El spread compensa costes y riesgos bajo las reglas del venue.", "El inventario puede requerir cobertura.", "La actividad observada no revela todos los objetivos internos del participante."] },
    { type: "callout", title: "No forzar equivalencias", text: "Market maker y dealer son conceptos relacionados, pero no deben tratarse como una identidad única en todos los mercados." },
  ],
  "options-foundations-16-hedging": [
    { type: "heading", level: 2, text: "Reducir una exposición" },
    { type: "paragraph", text: "Hedging significa tomar una posición compensatoria para reducir la sensibilidad a un riesgo. Una cartera con exposición positiva al precio puede añadir una posición negativa en otro instrumento, aunque la cobertura nunca elimina todos los riesgos." },
    { type: "paragraph", text: "Una cobertura puede ser estática —se mantiene durante un periodo— o dinámica —se ajusta cuando cambian precio, Delta, volatilidad o composición de la cartera—." },
    { type: "list", items: ["Identifica el riesgo que quieres reducir.", "Elige un instrumento con relación razonable a ese riesgo.", "Calcula que la cobertura es aproximada y puede cambiar.", "Considera liquidez, costes, basis y riesgos residuales."] },
    { type: "callout", title: "Ejemplo", text: "Compensar una Delta positiva con exposición negativa reduce sensibilidad local, pero no elimina Gamma, Vega, Theta, liquidez ni otros riesgos." },
  ],
  "options-foundations-17-delta-hedging": [
    { type: "heading", level: 2, text: "Compensar Delta con el subyacente" },
    { type: "paragraph", text: "Delta hedging busca reducir la exposición direccional local de una cartera de opciones usando el subyacente, futuros o un instrumento relacionado. Si una posición tiene Delta aproximada de +0,40 BTC equivalente, una cobertura cercana a -0,40 BTC puede reducir esa Delta en ese momento." },
    { type: "paragraph", text: "La cobertura no queda fija: Delta cambia cuando cambia el spot, por Gamma, por el paso del tiempo o por la volatilidad. Por eso una cartera real puede requerir ajustes y agregación de muchos contratos." },
    { type: "list", items: ["Es una aproximación local, no una garantía de neutralidad permanente.", "El hedge puede introducir costes y riesgo de ejecución.", "Gamma hace que la cobertura necesaria evolucione.", "No podemos inferir la cobertura real de un dealer únicamente desde OI."] },
    { type: "callout", title: "Fundamento", text: "Delta hedging explica una mecánica de gestión de riesgo; no demuestra qué está haciendo un participante concreto." },
  ],
  "options-foundations-18-deribit": [
    { type: "heading", level: 2, text: "Una venue importante para cripto opciones" },
    { type: "paragraph", text: "Deribit es una venue utilizada para observar y negociar opciones de criptoactivos. En la superficie actual de GoodTrading, el módulo Options consulta un libro de opciones Deribit para BTC o ETH y permite seleccionar una expiración." },
    { type: "heading", level: 3, text: "Datos que expone la integración" },
    { type: "list", items: ["Precio subyacente y expiraciones disponibles.", "Filas organizadas por strike.", "Call y Put por strike.", "Open Interest, volumen de 24 horas y precios Bid/Ask.", "Delta e implied volatility Bid/Ask cuando están disponibles.", "Datos de liquidez y marcas temporales de actualización."] },
    { type: "paragraph", text: "La integración también calcula o muestra métricas derivadas para la visualización. Es importante distinguir esos campos de una lectura directa de intención: el módulo organiza datos y modelos, no revela automáticamente el lado real de cada participante." },
    { type: "callout", title: "Alcance actual", text: "La interfaz soporta BTC y ETH en el módulo Options. Eso no significa que todos los activos estén habilitados en el selector general del Terminal ni que cada campo esté disponible en todo momento." },
  ],
  "options-foundations-19-expirations": [
    { type: "heading", level: 2, text: "Varios relojes en la misma superficie" },
    { type: "paragraph", text: "En cripto opciones pueden coexistir múltiples expiraciones. Cada una tiene su propio conjunto de strikes, Open Interest, volatilidad y sensibilidades. Una cadena corta y una cadena larga pueden responder de manera diferente ante el mismo movimiento del subyacente." },
    { type: "list", items: ["Short-dated: menos tiempo y, a menudo, mayor sensibilidad al paso del tiempo.", "Longer-dated: más tiempo para que cambien spot, IV y estructura.", "La distribución de OI puede concentrarse en expiraciones distintas.", "Sumar todas las expiraciones sin separar el horizonte puede ocultar estructura."] },
    { type: "paragraph", text: "El módulo Deribit permite escoger una expiración y muestra su fecha en formato de la cadena. Estudiar una expiración es una forma de conservar contexto; no implica una regla para priorizarla operativamente." },
    { type: "callout", title: "Contexto", text: "La fecha de vencimiento es parte de la identidad de la opción. OI de dos expiraciones no es necesariamente comparable como si fuera una sola posición." },
  ],
  "options-foundations-20-btc-options": [
    { type: "heading", level: 2, text: "La superficie de opciones sobre BTC" },
    { type: "paragraph", text: "Las opciones sobre BTC se organizan por strike, expiración, tipo de contrato y variables de valoración. La cadena permite observar Open Interest, volumen, cotizaciones e información de Greeks cuando está disponible." },
    { type: "paragraph", text: "Estas posiciones pueden influir en la gestión de riesgo de participantes que cubren con BTC, futuros o perpetuals. La relación es contextual: tamaño, liquidez, tiempo, volatilidad y estructura de la cartera determinan cuánto puede importar una exposición." },
    { type: "list", items: ["BTC spot es el subyacente de referencia, no la opción misma.", "Strikes y expiraciones organizan la superficie.", "OI no identifica el lado long/short.", "Greeks describen sensibilidades modeladas, no resultados futuros garantizados."] },
    { type: "callout", title: "Uso educativo", text: "Observar BTC options ayuda a ampliar el contexto de derivados; no implica que las opciones dominen mecánicamente cada movimiento del spot." },
  ],
  "options-foundations-21-eth-options": [
    { type: "heading", level: 2, text: "Una superficie distinta sobre ETH" },
    { type: "paragraph", text: "Las opciones sobre ETH siguen la misma estructura conceptual: Calls y Puts, strikes, expiraciones, prima, Open Interest y sensibilidades. Pero su liquidez, distribución de posiciones y comportamiento pueden diferir de BTC." },
    { type: "paragraph", text: "El módulo Options del Terminal actual puede consultar currency BTC o ETH en la integración Deribit. Sin embargo, el selector general de activos del desktop mantiene BTC como activo habilitado y muestra ETH como próximamente disponible. Esta lesson enseña el mercado de ETH options, no afirma que ETH esté habilitado en cada superficie del producto." },
    { type: "list", items: ["No mezcles la estructura de ETH con la de BTC sin revisar expiración y liquidez.", "La presencia de OI no revela automáticamente dirección.", "Los mismos Greeks pueden tener magnitudes y sensibilidad diferentes."] },
    { type: "callout", title: "Producto vs concepto", text: "La integración específica de Options soporta ETH; la disponibilidad del activo general depende de la superficie del Terminal que estés usando." },
  ],
  "options-foundations-22-why-options-matter": [
    { type: "heading", level: 2, text: "Una capa de contexto adicional" },
    { type: "paragraph", text: "Las opciones pueden importar porque grandes carteras acumulan exposiciones que cambian con el spot, el tiempo y la volatilidad. Los participantes pueden cubrir esas exposiciones mediante el subyacente, futuros o perpetuals, generando flujos que forman parte del entorno de mercado." },
    { type: "list", items: ["No todo movimiento de BTC o ETH es causado por opciones.", "La inferencia de posicionamiento requiere supuestos.", "La liquidez del spot y futuros sigue siendo relevante.", "Order Flow y respuesta del precio aportan otra capa de evidencia.", "Los datos de opciones son contexto, no una orden automática."] },
    { type: "paragraph", text: "Gamma, Vanna, Charm, OI y Delta ayudan a describir sensibilidades y posibles necesidades de cobertura. Para convertirlos en una interpretación concreta hacen falta definiciones, calidad de datos y una separación clara entre observación e inferencia." },
    { type: "callout", title: "Siguiente curso", text: "Gamma & Dealer Hedging profundiza en estos conceptos. Esta introducción no incluye zonas, setups, confluencias ni reglas operativas de GoodTrading." },
  ],
};
