import type { AcademyContentBlock } from "@shared/academy-content";

const lesson = (title: string, paragraph: string, items: string[], callout: string): AcademyContentBlock[] => [
  { type: "heading", level: 2, text: title },
  { type: "paragraph", text: paragraph },
  { type: "list", items },
  { type: "callout", title: "Research discipline", text: callout },
];

export const STRATEGY_LAB_AND_RESEARCH_CONTENT: Record<string, AcademyContentBlock[]> = {
  "strategy-lab-and-research-01-hypothesis": lesson("Una hipótesis falsable", "Una estrategia empieza con una afirmación que puede fallar. En vez de decir que el precio suele subir, formula una relación observable: cuando existe una condición X, el comportamiento Y podría aparecer con más frecuencia que una referencia definida.", ["Nombra las variables observables.", "Explica la relación esperada.", "Define qué resultado la debilitaría.", "Usa ejemplos genéricos o sintéticos.", "Separa una pregunta de investigación de una promesa."], "Una hipótesis útil puede ser contradicha por los datos; si siempre puede explicarse después, no es falsable."),
  "strategy-lab-and-research-02-signal": lesson("Señal no es estrategia", "Una señal es un evento observable o un estado derivado que podría contener información: desplazamiento de precio, expansión de volumen, transición de volatilidad o una variable técnica pública. Sin contexto, reglas y validación, una señal no demuestra edge.", ["Describe el evento sin atribuirle intención.", "Indica si es observado o derivado.", "Define la referencia contra la que se compara.", "Evita convertir un print aislado en una decisión.", "Documenta cuándo la señal no está disponible."], "El nombre de una señal no reemplaza una hipótesis, una regla de ejecución ni una evaluación honesta."),
  "strategy-lab-and-research-03-condition": lesson("Condición y entorno", "Una condición define el entorno en el que una hipótesis debe evaluarse. Puede referirse a volatilidad contextual, un régimen definido por el investigador o una relación con una estructura pública. Condición y trigger no son sinónimos.", ["Haz que la condición sea observable.", "Defínela antes de mirar el resultado.", "Evita términos ambiguos como fuerte o limpio.", "Declara la fuente y el timestamp.", "GoodTrading no tiene hoy un schema canónico de condiciones de Strategy Lab."], "Aquí estudiamos metodología de research; no se presenta un contrato de runtime que el producto actual no tiene."),
  "strategy-lab-and-research-04-entry": lesson("Definir una entrada investigable", "Una estrategia evaluable debe especificar qué cuenta como entrada. La investigación necesita una definición del evento, su timestamp, una suposición de precio y una suposición de orden. Sin esas decisiones, el resultado no es reproducible.", ["Describe el evento que habilita la entrada.", "Fija qué información estaba disponible en ese instante.", "Declara la suposición de precio.", "Declara el tipo de ejecución simulado.", "No uses timing propietario de BTC como ejemplo."], "La entrada de un estudio es una convención explícita, no una reconstrucción retrospectiva conveniente."),
  "strategy-lab-and-research-05-exit": lesson("La salida también define el resultado", "No se puede evaluar una estrategia mirando solo la entrada. La salida cambia el PnL, la duración, el drawdown y la distribución de resultados. Puedes investigar salidas por invalidación de tesis, estructura, tiempo o una regla fija pública.", ["Escribe la salida antes de revisar el resultado.", "Distingue salida por tesis de salida por tiempo.", "Declara cómo se trata una salida parcial si existe.", "Mantén constantes las suposiciones entre muestras.", "No copies jerarquías de targets de GoodTrading."], "Una entrada idéntica puede producir conclusiones opuestas bajo salidas distintas; por eso la salida pertenece al diseño."),
  "strategy-lab-and-research-06-invalidation": lesson("Invalidación, salida y entrada", "Entrada es el punto en que una hipótesis se vuelve accionable dentro del test. Salida es el momento en que la posición simulada termina. Invalidación es el punto en que la hipótesis original deja de ser una explicación útil. Pueden coincidir, pero no significan lo mismo.", ["Define qué evidencia contradice la hipótesis.", "No confundas fluctuación con invalidación.", "Registra la decisión con información disponible entonces.", "Separa invalidación conceptual de una guardia de ejecución.", "No publiques thresholds de Course 11 o 12."], "Si la investigación no puede explicar qué la haría abandonar la tesis, todavía no tiene un criterio falsable."),
  "strategy-lab-and-research-07-what-is-a-backtest": lesson("Backtest como método de investigación", "Un backtest aplica reglas predefinidas a datos históricos para estudiar cómo se habrían comportado bajo supuestos declarados. No prueba rentabilidad futura. GoodTrading no expone actualmente un motor de backtesting de estrategias en un Strategy Lab funcional.", ["Congela las reglas antes de recorrer la muestra.", "Declara fuente, rango y calidad de datos.", "Recorre los eventos cronológicamente.", "Registra resultados y datos faltantes.", "No escribas un workflow de abrir Strategy Lab y pulsar Run Test."], "La metodología es enseñable hoy; la automatización del producto no debe inventarse."),
  "strategy-lab-and-research-08-sample-size": lesson("Tamaño y diversidad de muestra", "Las muestras pequeñas producen conclusiones inestables. El número de observaciones importa, pero también su independencia, la diversidad de regímenes, la frecuencia de setups raros y la estabilidad de la distribución.", ["Cuenta observaciones y eventos elegibles.", "Describe dependencia entre operaciones.", "Incluye más de un contexto de mercado cuando sea posible.", "No inventes un mínimo universal de trades.", "GoodTrading no impone hoy mínimo, intervalo de confianza, significancia ni bootstrap."], "Un resultado llamativo con poca evidencia debe conservar incertidumbre explícita."),
  "strategy-lab-and-research-09-in-sample": lesson("In-sample", "El conjunto in-sample se usa para construir o refinar una hipótesis. Esa utilidad crea riesgo: cuanto más se ajustan reglas a esa muestra, más fácil es capturar ruido en lugar de una relación repetible.", ["Declara qué decisiones se tomaron mirando la muestra.", "Registra cada cambio de regla.", "No uses la misma evidencia para validar y construir.", "Mantén parámetros y supuestos visibles.", "GoodTrading no automatiza hoy una partición IS."], "In-sample sirve para aprender; no debe presentarse como prueba independiente."),
  "strategy-lab-and-research-10-out-of-sample": lesson("Out-of-sample", "El conjunto out-of-sample no se utiliza para construir la estrategia. Su propósito es observar si el comportamiento sobrevive fuera de la muestra de desarrollo, con reglas congeladas y sin ajustes oportunistas.", ["Separa la muestra antes de revisar resultados.", "No modifiques reglas durante el recorrido.", "Compara degradación y distribución, no solo PnL.", "Documenta diferencias de fuente o calidad.", "No hay split automático ni walk-forward actual en GoodTrading."], "OOS es una disciplina metodológica manual en el estado actual del producto."),
  "strategy-lab-and-research-11-overfitting": lesson("Sobreajuste", "El sobreajuste aparece cuando una estrategia captura ruido o idiosincrasias de una muestra en lugar de una estructura repetible. Más parámetros no significan más conocimiento.", ["Observa fragilidad ante cambios pequeños.", "Cuestiona muchos filtros y thresholds.", "Busca estabilidad entre regímenes.", "Desconfía de repetir ajustes hasta obtener un resultado atractivo.", "GoodTrading no detecta sobreajuste automáticamente."], "La investigación debe preferir una explicación simple y falsable antes que una curva perfecta."),
  "strategy-lab-and-research-12-lookahead-bias": lesson("Lookahead bias", "Hay lookahead bias cuando el test usa información que no estaba disponible en el timestamp de decisión. Puede aparecer con el cierre futuro de una vela, un high/low posterior, indicadores revisados o valores de opciones y OI conocidos después.", ["Pregunta qué sabía el investigador en cada evento.", "No uses el cierre futuro para definir una entrada pasada.", "No reemplaces datos originales por revisiones posteriores.", "Verifica timestamp y latencia de cada fuente.", "Gamma y OI requieren especial cuidado de punto en el tiempo."], "GoodTrading no garantiza hoy prevención automática de lookahead; la responsabilidad pertenece al diseño del estudio."),
  "strategy-lab-and-research-13-expected-value": lesson("Expected Value", "La expectativa puede expresarse conceptualmente como EV = P(win) × Average Win − P(loss) × Average Loss. Es una propiedad estadística de una distribución estimada, no una garantía para el próximo trade.", ["Define cómo estimas frecuencia de wins y losses.", "Mantén unidades y muestra consistentes.", "Incluye costos cuando sean parte del estudio.", "Observa incertidumbre y sensibilidad.", "La salida de expectancy de Strategy Lab no está implementada."], "Una EV positiva no elimina drawdown, varianza ni riesgo de que el modelo esté mal especificado."),
  "strategy-lab-and-research-14-profit-factor": lesson("Profit Factor", "Profit Factor compara gross profits con gross losses. Puede resumir la relación entre ganancias y pérdidas, pero depende de la muestra, los costos, los outliers y de cómo se definieron las operaciones.", ["Define gross profit y gross loss antes del cálculo.", "Aclara si los costos están incluidos.", "Muestra trade count y distribución junto al ratio.", "No uses el ratio aislado como prueba.", "Strategy Lab no calcula hoy Profit Factor como output actual."], "Los reportes Paper existentes no deben confundirse con un bundle de resultados de Strategy Lab."),
  "strategy-lab-and-research-15-drawdown": lesson("Drawdown", "Drawdown es la caída desde un pico previo de equity. Una pérdida individual y un drawdown no son la misma observación: el segundo incorpora profundidad, duración y secuencia de resultados.", ["Registra la curva de equity definida por el estudio.", "Separa profundidad de duración.", "Observa secuencias adversas.", "Declara si el cálculo es bruto o neto de costos.", "No afirmes que Strategy Lab produce max drawdown hoy."], "El riesgo de secuencia puede ser importante incluso cuando el resultado agregado parece atractivo."),
};
