import type { AcademyContentBlock } from "@shared/academy-content";

export const TERMINAL_QUICKSTART_CONTENT: Record<string, AcademyContentBlock[]> = {
  "terminal-quickstart-01-welcome-to-goodtrading": [
    { type: "heading", level: 2, text: "Un entorno para leer antes de decidir" },
    { type: "paragraph", text: "GoodTrading Terminal reúne información de mercado en una sola superficie: precio, contexto, posicionamiento, liquidez, flujo y herramientas de ejecución simulada. Su función es ayudarte a observar y ordenar evidencia; no decide por ti ni promete resultados." },
    { type: "heading", level: 3, text: "El objetivo de la Academy" },
    { type: "paragraph", text: "La Academy construye una base común antes de entrar en interpretaciones avanzadas. Primero aprenderás a orientarte, después a leer cada fuente de información y finalmente a combinar contexto con una decisión prudente." },
    { type: "list", items: ["Distinguir un dato observado de una interpretación.", "Entender qué pregunta responde cada panel.", "Esperar evidencia suficiente antes de actuar.", "Usar Paper Trading para practicar la plataforma sin arriesgar capital real."] },
    { type: "callout", title: "Idea central", text: "Una herramienta puede reducir incertidumbre, pero no elimina el riesgo. El Terminal informa; la decisión y su responsabilidad siguen siendo del operador." },
  ],
  "terminal-quickstart-02-how-the-terminal-is-organized": [
    { type: "heading", level: 2, text: "La superficie principal" },
    { type: "paragraph", text: "La vista Terminal está organizada alrededor de una barra superior, un gráfico central y paneles laterales e inferiores. La barra superior permite cambiar entre Terminal, Options, Flows, Volatility, Reports y Alerts; también muestra el activo, el timeframe, el feed y el estado de conexión." },
    { type: "heading", level: 3, text: "Regiones que encontrarás" },
    { type: "list", items: ["Barra superior: navegación de módulos y acceso a alertas y usuario.", "Barra de contexto: activo BTC, expiración cuando está disponible, timeframe, feed Deribit y zona horaria.", "Gráfico central: la superficie principal para observar precio y contexto temporal.", "Panel lateral izquierdo: Market State, exposición, posicionamiento y Key Levels.", "Panel lateral derecho: Market Mode, Trading State, Liquidity Map, Options Snapshot y otros módulos.", "Panel inferior: conexión y ejecución Paper Trading."] },
    { type: "paragraph", text: "Los paneles pueden ocultarse para concentrarte en el gráfico. La vista cambia de densidad, pero la jerarquía es la misma: identifica el instrumento y el contexto antes de interpretar un detalle." },
    { type: "callout", title: "Orientación", text: "No necesitas leer todos los paneles al mismo tiempo. Empieza por ubicarte; luego elige la fuente que responda a tu pregunta." },
  ],
  "terminal-quickstart-03-selecting-an-instrument": [
    { type: "heading", level: 2, text: "Instrumento, símbolo y mercado" },
    { type: "paragraph", text: "Un instrumento es el mercado concreto que estás observando. El símbolo es su identificador abreviado; por ejemplo, el selector actual de la aplicación muestra BTC. El mercado o venue indica dónde se obtiene o ejecuta esa información cuando la interfaz lo expone." },
    { type: "heading", level: 3, text: "Estado actual del selector" },
    { type: "paragraph", text: "La superficie desktop tiene un selector de activos. BTC es el activo habilitado; ETH, NASDAQ, SP500 y XAUUSD aparecen como opciones próximas, no como mercados actualmente activos. En la vista web, la barra de contexto también presenta Asset: BTC." },
    { type: "list", items: ["Confirma el símbolo antes de leer niveles o comparar precios.", "Verifica que los datos y la ejecución simulada correspondan al mismo contexto.", "No infieras que una opción marcada como próxima ya está disponible."] },
    { type: "callout", title: "Regla práctica", text: "Un análisis correcto sobre el instrumento equivocado sigue siendo un análisis equivocado." },
  ],
  "terminal-quickstart-04-spot-vs-perpetual": [
    { type: "heading", level: 2, text: "Dos formas de exponerse al precio" },
    { type: "paragraph", text: "En Spot compras o vendes el activo subyacente. En un Perpetual operas un contrato sin fecha de vencimiento fija, cuyo precio busca mantenerse cerca del mercado de referencia. Ambos pueden seguir a BTC, pero no representan exactamente la misma cosa." },
    { type: "heading", level: 3, text: "Por qué pueden diferir" },
    { type: "paragraph", text: "Cada mercado tiene su propia liquidez, participantes y mecanismo de financiación. En un Perpetual, el funding es un pago periódico entre participantes que ayuda a mantener el contrato cerca del índice; no es una garantía de convergencia perfecta ni una señal de dirección por sí sola." },
    { type: "paragraph", text: "En el Terminal actual, el contexto general muestra BTC y la ruta de ejecución simulada construye órdenes para un mercado perpetual en BingX. Eso no significa que la superficie exponga un selector completo Spot/Perpetual para todos los instrumentos. La distinción sigue siendo necesaria para no mezclar fuentes." },
    { type: "callout", title: "Concepto clave", text: "Antes de comparar precio, volumen o niveles, confirma qué mercado representa cada dato. Spot y Perpetual no deben tratarse como una única verdad indiferenciada." },
  ],
  "terminal-quickstart-05-timeframes": [
    { type: "heading", level: 2, text: "Qué representa un timeframe" },
    { type: "paragraph", text: "Un timeframe define cuánto tiempo resume cada vela. Una vela de 1m agrega aproximadamente un minuto de actividad; no muestra cada evento individual, sino una síntesis de apertura, máximo, mínimo y cierre junto con el volumen disponible." },
    { type: "heading", level: 3, text: "Timeframes disponibles" },
    { type: "list", items: ["15s: vista muy corta para observar cambios rápidos.", "1m: timeframe predeterminado del gráfico.", "5m: contexto intradía más amplio.", "15m: estructura de corto plazo y referencia contextual."] },
    { type: "paragraph", text: "Un timeframe mayor ayuda a ubicar contexto; uno menor permite observar el desarrollo inmediato. Ninguno es automáticamente mejor. La ejecución, cuando corresponda, debe interpretarse dentro de un contexto suficiente y no como reacción aislada a una vela." },
    { type: "callout", title: "Recuerda", text: "Cambiar el timeframe cambia la agregación de los datos, no el mercado subyacente." },
  ],
  "terminal-quickstart-06-layouts-and-panels": [
    { type: "heading", level: 2, text: "Organizar la atención" },
    { type: "paragraph", text: "El Terminal reúne muchas fuentes: gráfico, Market State, Gamma, posicionamiento, Liquidity Map, escenarios, alertas y ejecución. La utilidad no está en mostrarlo todo, sino en mantener visible lo que responde a la pregunta actual." },
    { type: "heading", level: 3, text: "Disciplina de paneles" },
    { type: "list", items: ["Empieza con el gráfico y la barra de contexto.", "Abre un panel porque necesitas una evidencia concreta.", "Oculta paneles que agreguen ruido o repitan la misma información.", "Separa lectura de mercado de preparación de ejecución."] },
    { type: "paragraph", text: "La aplicación permite alternar la visibilidad de los paneles y minimizar los paneles inferiores. Esas preferencias se conservan localmente para la interfaz. No hay que confundir esa comodidad con un sistema completo de layouts nombrados y sincronizados entre dispositivos." },
    { type: "callout", title: "Jerarquía", text: "Más paneles no equivale a más claridad. Una superficie pequeña y relevante suele ser más útil que una pared de indicadores." },
  ],
  "terminal-quickstart-07-bid-ask-mid-and-last": [
    { type: "heading", level: 2, text: "Cuatro precios relacionados, no intercambiables" },
    { type: "paragraph", text: "El Bid es el mejor precio visible al que alguien ofrece comprar. El Ask es el mejor precio visible al que alguien ofrece vender. Entre ambos existe el Spread: la distancia entre compra y venta disponible." },
    { type: "heading", level: 3, text: "Mid y Last" },
    { type: "list", items: ["Mid: punto medio entre Bid y Ask; sirve como referencia matemática.", "Last: precio de la última operación ejecutada.", "Spread: coste implícito de cruzar desde una cotización a la otra.", "Bid y Ask: precios disponibles, sujetos a cambios y profundidad."] },
    { type: "paragraph", text: "El Last puede estar por encima o por debajo del Mid según dónde ocurrió la última operación. El Mid puede no ser un precio ejecutable. Por eso una lectura de mercado debe indicar si está hablando de cotización, referencia o transacción realizada." },
    { type: "callout", title: "Idea clave", text: "Precio cotizado y precio negociado describen momentos distintos del mercado. No los uses como sinónimos." },
  ],
  "terminal-quickstart-08-price-and-volume": [
    { type: "heading", level: 2, text: "Precio y actividad negociada" },
    { type: "paragraph", text: "El precio resume dónde se cruzaron las operaciones y cómo cambia su valor de referencia. El volumen resume cuánto se negoció dentro del intervalo que estás observando. Juntos describen actividad, pero no explican por sí solos quién tendrá razón después." },
    { type: "heading", level: 3, text: "El contexto importa" },
    { type: "list", items: ["Compara el volumen con velas y sesiones de escala similar.", "Observa si el precio avanzó, retrocedió o quedó contenido.", "Distingue actividad puntual de una secuencia persistente.", "No conviertas una barra de volumen en una predicción automática."] },
    { type: "paragraph", text: "Un volumen alto puede acompañar continuación, rechazo, absorción o simplemente un momento de alta participación. Para profundizar en agresión, volumen ejecutado y delta, la Academy continúa con Order Flow Foundations." },
    { type: "callout", title: "Precisión", text: "Volumen informa cuánto se negoció; no indica dirección por sí mismo." },
  ],
  "terminal-quickstart-09-understanding-each-panel": [
    { type: "heading", level: 2, text: "Un mapa rápido de la interfaz" },
    { type: "paragraph", text: "Cada panel responde una pregunta diferente. Antes de interpretar un valor, identifica su dominio y su frecuencia de actualización." },
    { type: "list", items: ["Market State: régimen Gamma y referencias agregadas del estado de mercado.", "Dealer Exposure y Hedging Flow: exposición y flujo de cobertura de opciones cuando hay datos.", "Options Positioning y Key Levels: posicionamiento y niveles calculados visibles.", "Liquidity Map: representación de liquidez y zonas relacionadas cuando están disponibles.", "Order Flow / Flows: actividad de flujo en su módulo correspondiente.", "Alerts: historial, filtros y preferencias de alertas.", "Panel inferior: conexión y Paper Trading."] },
    { type: "paragraph", text: "Algunos valores pueden mostrar --, N/A o estados de indisponibilidad. Eso es distinto de cero: significa que no hay un dato utilizable en ese momento. Aprende a leer también la calidad y disponibilidad de la información." },
    { type: "callout", title: "Método", text: "Primero pregunta qué mide el panel; después pregunta qué puedes concluir. Nunca al revés." },
  ],
  "terminal-quickstart-10-gamma-panel-overview": [
    { type: "heading", level: 2, text: "Gamma como contexto de posicionamiento" },
    { type: "paragraph", text: "Gamma describe cómo cambia la sensibilidad de una posición de opciones ante movimientos del subyacente. En conjunto, las posiciones de opciones pueden influir en cómo ciertos participantes cubren su exposición." },
    { type: "heading", level: 3, text: "Qué muestra el Terminal" },
    { type: "paragraph", text: "La interfaz actual expone información como Gamma Regime, Total GEX, Global Flip, Local Flip, Dealer Exposure, Dealer Hedging Flow, Options Positioning y Key Levels. También indica cuándo los datos de opciones están desactualizados o no disponibles." },
    { type: "paragraph", text: "Un nivel o régimen de Gamma es una pieza de contexto, no una orden ni una señal independiente. Su interpretación depende del instrumento, la calidad del snapshot y la relación con precio y participación." },
    { type: "callout", title: "Límite sano", text: "Gamma puede ayudar a formular preguntas sobre el entorno; no reemplaza el análisis ni garantiza una reacción del precio." },
  ],
  "terminal-quickstart-11-order-flow-panel-overview": [
    { type: "heading", level: 2, text: "Leer la actividad ejecutada" },
    { type: "paragraph", text: "Order Flow observa cómo se ejecutan las operaciones, no solo cómo queda dibujada una vela. A nivel introductorio, permite estudiar la participación compradora y vendedora, y distinguir actividad más agresiva de liquidez pasiva que espera ser negociada." },
    { type: "heading", level: 3, text: "Por qué aporta otra perspectiva" },
    { type: "list", items: ["Una vela muestra el resultado agregado del intervalo.", "El flujo ayuda a investigar el proceso de negociación dentro de ese intervalo.", "La agresión describe órdenes que cruzan liquidez disponible.", "La participación pasiva describe liquidez que permanece ofrecida o demandada."] },
    { type: "paragraph", text: "El Terminal tiene una sección FLOWS en la navegación superior y componentes de flujo en sus paneles. Esta lesson solo orienta: las lecturas de delta, absorción y subastas pertenecen al curso Order Flow Foundations." },
    { type: "callout", title: "Principio", text: "El precio es el resultado observable; el flujo ayuda a estudiar el proceso que lo produjo." },
  ],
  "terminal-quickstart-12-liquidity-heatmap-overview": [
    { type: "heading", level: 2, text: "Liquidez que espera ser negociada" },
    { type: "paragraph", text: "La liquidez resting son órdenes que permanecen visibles en el libro y pueden cambiar antes de ejecutarse. Una heatmap agrega esa información a través del tiempo para mostrar dónde hubo más o menos presencia relativa de órdenes." },
    { type: "heading", level: 3, text: "Qué observar con cuidado" },
    { type: "list", items: ["Persistencia: si una zona permanece visible o desaparece rápido.", "Distancia: relación entre la liquidez y el precio actual.", "Cambio: migración, cancelación o reposición de órdenes.", "Resultado: si el precio interactuó con la zona y qué ocurrió después."] },
    { type: "paragraph", text: "El Terminal incluye Liquidity Map y una superficie Heatmap en sus módulos. La visualización es histórica y contextual; una pared visible no es automáticamente soporte o resistencia, porque puede cancelarse o ser atravesada." },
    { type: "callout", title: "No confundir", text: "Una pared de liquidez es información sobre intención visible, no una promesa de defensa del precio." },
  ],
  "terminal-quickstart-13-alerts": [
    { type: "heading", level: 2, text: "Alertas para observar sin vigilar cada segundo" },
    { type: "paragraph", text: "Una alerta notifica que ocurrió un evento o que una condición configurada requiere atención. Su valor es reducir la vigilancia constante, no sustituir la revisión del contexto cuando llega la notificación." },
    { type: "heading", level: 3, text: "Comportamiento disponible" },
    { type: "list", items: ["El botón de campana abre el Centro de alertas.", "El Centro muestra historial y permite filtrar por estado, severidad, dominio y símbolo.", "Los dominios actuales incluyen gamma, market, flow, account y system.", "Puedes marcar alertas como leídas, reconocerlas o descartarlas.", "Las preferencias incluyen activar o desactivar alertas."] },
    { type: "paragraph", text: "El Centro también comunica estados como sistema deshabilitado, falta de sesión o historial no disponible. Una alerta cargada con error no debe interpretarse como ausencia de eventos." },
    { type: "callout", title: "Uso responsable", text: "Una alerta llama tu atención; todavía debes confirmar instrumento, timeframe, datos y contexto antes de tomar una decisión." },
  ],
  "terminal-quickstart-14-analyze-btc-in-five-minutes": [
    { type: "heading", level: 2, text: "Un recorrido breve y repetible" },
    { type: "paragraph", text: "Este ejercicio no busca encontrar una operación. Busca comprobar si puedes construir una lectura ordenada de BTC sin saltar directamente al gatillo." },
    { type: "heading", level: 3, text: "Secuencia de cinco minutos" },
    { type: "list", items: ["Instrumento: confirma que estás observando BTC y que la fuente corresponde al mercado que quieres estudiar.", "Contexto: elige 5m o 15m para ubicar la estructura; usa 1m o 15s solo para observar el detalle inmediato.", "Niveles: revisa los Key Levels y las referencias visibles, sin asumir que todos serán defendidos.", "Información actual: contrasta precio, volumen y los paneles disponibles de liquidez, flujo o posicionamiento.", "Decisión conceptual: si la evidencia es incompleta o contradictoria, la respuesta válida es esperar."] },
    { type: "paragraph", text: "Anota qué viste y qué no pudiste confirmar. Esa diferencia evita rellenar huecos con una narrativa. Los marcos de Market Structure, Order Flow y GoodTrading Playbook desarrollan después cómo estudiar cada componente con mayor profundidad." },
    { type: "callout", title: "Resultado buscado", text: "Una buena primera lectura no termina necesariamente en Trade. También puede terminar en Wait con una razón clara." },
  ],
  "terminal-quickstart-15-save-your-workspace": [
    { type: "heading", level: 2, text: "Organizar no es lo mismo que guardar un layout" },
    { type: "paragraph", text: "Un workspace útil mantiene a mano el gráfico, el contexto y los paneles que realmente consultas. Conviene ordenar la interfaz antes de estudiar para que cada revisión empiece desde una superficie conocida." },
    { type: "heading", level: 3, text: "Qué permite actualmente el producto" },
    { type: "list", items: ["Puedes mostrar u ocultar los paneles del Terminal.", "Puedes minimizar los paneles inferiores de conexión y ejecución.", "La aplicación conserva esas preferencias localmente en el dispositivo.", "La persistencia de estilos de herramientas de dibujo también existe como configuración local."] },
    { type: "paragraph", text: "La implementación actual no expone un flujo completo de guardar, nombrar y sincronizar múltiples layouts de workspace. Por eso esta lesson enseña organización práctica, no un botón de guardado que la interfaz todavía no ofrece." },
    { type: "callout", title: "Hábitat de trabajo", text: "El mejor workspace es el que hace visible la evidencia necesaria y mantiene fuera de foco lo que no estás usando." },
  ],
  "terminal-quickstart-16-create-your-first-alert": [
    { type: "heading", level: 2, text: "Configurar una señal de atención" },
    { type: "paragraph", text: "Tu primera alerta debe responder a una pregunta concreta: qué evento quieres revisar cuando ocurra. No la uses para delegar la decisión; úsala para volver al Terminal en el momento adecuado." },
    { type: "heading", level: 3, text: "Flujo real de revisión" },
    { type: "list", items: ["Abre el Centro de alertas desde la campana de la barra superior.", "Revisa el estado de Alertas activas y las preferencias disponibles.", "Cuando exista un evento, usa el historial y filtra por símbolo, dominio, severidad o estado.", "Lee el detalle y reconoce, marca como leída o descarta la alerta según corresponda."] },
    { type: "paragraph", text: "La interfaz actual confirma que el Centro gestiona historial, filtros y preferencias. Los tipos exactos de condiciones se determinan por los eventos que el sistema produzca; no inventes una condición que no aparezca en la configuración disponible." },
    { type: "callout", title: "Ejercicio", text: "Después de revisar una alerta, escribe qué información adicional necesitas confirmar en el gráfico antes de actuar." },
  ],
  "terminal-quickstart-17-introduction-to-paper-trading": [
    { type: "heading", level: 2, text: "Practicar la mecánica sin capital real" },
    { type: "paragraph", text: "Paper Trading es una sesión de ejecución simulada. Sirve para aprender la interfaz, revisar una orden, observar posiciones y practicar una rutina sin enviar una orden real a un broker." },
    { type: "heading", level: 3, text: "Qué ofrece la superficie actual" },
    { type: "list", items: ["El panel inferior incluye el bloque de ejecución y la sesión Paper.", "El ticket contempla lado, tipo, tamaño, unidad, precio para órdenes limit, leverage, margin mode y controles de riesgo.", "La interfaz muestra posiciones y órdenes simuladas y permite gestionar cierres según el estado de la sesión.", "La ruta Paper usa el contexto perpetual de BingX simulado y valida símbolos, precio y parámetros antes de enviar."] },
    { type: "paragraph", text: "La simulación no garantiza que los fills, latencia, liquidez o deslizamiento reproduzcan un mercado real. Úsala para practicar el flujo de la plataforma y registrar decisiones, no para asumir que un resultado simulado predice uno real." },
    { type: "callout", title: "Límite", text: "Paper Trading reduce el riesgo financiero de practicar, pero no elimina el riesgo de aprender una suposición incorrecta." },
  ],
  "terminal-quickstart-18-first-market-scan": [
    { type: "heading", level: 2, text: "Una lectura inicial sin buscar certeza" },
    { type: "paragraph", text: "Un market scan introductorio es una lista breve de comprobaciones. Su objetivo es decidir si existe suficiente información para seguir estudiando el mercado o si conviene esperar, no producir una entrada automática." },
    { type: "heading", level: 3, text: "Secuencia básica" },
    { type: "list", items: ["Confirma el mercado y el instrumento: empieza por BTC y verifica el contexto mostrado.", "Ubica el contexto temporal con 5m o 15m; baja a 1m solo para observar el desarrollo.", "Revisa los niveles visibles y su distancia al precio, sin tratarlos como certezas.", "Contrasta precio, volumen y la información disponible de liquidez, flujo o posicionamiento.", "Pregunta si los datos son suficientes, recientes y coherentes entre sí.", "Elige conceptualmente Trade o Wait; en esta lesson no se ejecuta ninguna orden ni se enseña una regla premium."] },
    { type: "paragraph", text: "Este scan es deliberadamente genérico. No incluye combinaciones de confluencias, gatillos, invalidaciones ni reglas del GoodTrading Market Scan premium del curso GoodTrading Playbook." },
    { type: "callout", title: "Cierre", text: "Esperar cuando la evidencia es insuficiente es una decisión de proceso, no un fracaso del análisis." },
  ],
};
