import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { pool } from "../../db";
import { ensureGoodTradingAccountForUser } from "../accounts/goodTradingAccountRepository";
import { createIntentWithInitialAttempt } from "../orders/goodTradingOrderIntentRepository";
import { getReconciliationRunByAttemptAndKey, createReconciliationRun } from "../orders/goodTradingOrderReconciliationRepository";
import { consumeBingXSubmissionReconciliation } from "./bingxSubmissionReconciliationPersistenceService";
import type { ReconciliationResult } from "./bingxSubmissionReconciliationService";

const suite = pool ? describe : describe.skip;
function input(accountUid: string, uid: string, key: string) { return { intent: { logicalOrderUid: uid, goodTradingAccountUid: accountUid, executionBroker: "BINGX", executionEnvironment: "LIVE", executionMarketInstrument: "BTC-USDT", executionMarketVenue: "BINGX", executionMarketType: "Perpetual" as const, canonicalBaseAsset: "BTC", canonicalQuoteAsset: "USDT", canonicalSettlementAsset: "USDT", canonicalProductType: "Perpetual" as const, canonicalContractStyle: "Linear" as const, canonicalExpiry: null, sourceNativeSymbol: "BTC-USDT", sourceNativeInstrumentId: null, marketMetadataSource: "server-owned-v1-registry", marketMappingPolicy: "EXACT_V1_REGISTRY", requestedSide: "buy" as const, orderType: "LIMIT" as const, requestedSize: "1", requestedSizeUnit: "BTC" as const, requestedSizingMode: "quantity" as const, resolvedQuantity: "1", resolvedQuantityUnit: "BTC" as const, limitPrice: "2", stopLossPrice: null, takeProfitPrice: null, timeInForce: "GTC" as const, postOnly: false, reduceOnly: false, requestIdempotencyKey: key }, attempt: { attemptId: `${uid}-ATTEMPT`, intentId: uid, attemptNumber: 1, brokerClientOrderId: `${uid}-CLIENT`, submittedQuantity: "1", transportState: "PERSISTED" as const, startedAt: null, responseAt: null, outcomeAt: null, reconciliationRequiredAt: null, brokerOrderId: null, rawBrokerStatus: null, httpStatus: null, errorCode: null, errorClass: null } }; }
async function fixture() { const marker = `${Date.now()}-${Math.random().toString(16).slice(2)}`; const user = await pool!.query("INSERT INTO users (email,password_hash,full_name) VALUES ($1,$2,$3) RETURNING id", [`b3b-${marker}@example.test`, "test", "B3-B3B"]); const userId = Number(user.rows[0].id); const account = await ensureGoodTradingAccountForUser(userId); const uid = `GT-B3B-${marker}`; await createIntentWithInitialAttempt(input(account.accountUid, uid, `key-${marker}`)); await pool!.query("UPDATE goodtrading_order_submission_attempts SET transport_state='RECONCILIATION_REQUIRED',reconciliation_required_at=now() WHERE id=$1", [`${uid}-ATTEMPT`]); return { userId, accountUid: account.accountUid, uid, attemptId: `${uid}-ATTEMPT`, client: `${uid}-CLIENT` }; }
async function cleanup(f: Awaited<ReturnType<typeof fixture>>) { await pool!.query("DELETE FROM goodtrading_broker_observation_snapshots WHERE broker_object_id IN (SELECT id FROM goodtrading_broker_objects WHERE broker_account_identity=$1)", [f.accountUid]); await pool!.query("DELETE FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$1", [f.accountUid]); await pool!.query("DELETE FROM goodtrading_broker_objects WHERE broker_account_identity=$1", [f.accountUid]); await pool!.query("DELETE FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1", [f.attemptId]); await pool!.query("DELETE FROM goodtrading_order_submission_attempts WHERE intent_id=$1", [f.uid]); await pool!.query("DELETE FROM goodtrading_order_intents WHERE id=$1", [f.uid]); await pool!.query("DELETE FROM goodtrading_accounts WHERE account_uid=$1", [f.accountUid]); await pool!.query("DELETE FROM users WHERE id=$1", [f.userId]); }
function matched(f: Awaited<ReturnType<typeof fixture>>, source: "OPEN_ORDERS" | "ORDER_HISTORY" = "OPEN_ORDERS"): ReconciliationResult { return { status: "MATCHED", logicalOrderUid: f.uid, brokerClientOrderId: f.client, sources: [source], observations: [{ source, clientOrderId: f.client, brokerOrderId: "987654321012345678", brokerOrderIdPrecisionTrusted: true, symbol: "BTC-USDT", side: "BUY", quantity: "1", price: "2", rawStatus: "NEW", observedAt: new Date().toISOString() }], sourceStatuses: { OPEN_ORDERS: "loaded", ORDER_HISTORY: "loaded", FILL_HISTORY: "loaded" }, absenceProven: false, retryAuthorized: false }; }
const sourceStatuses = { OPEN_ORDERS: "loaded", ORDER_HISTORY: "loaded", FILL_HISTORY: "loaded" } as const;

suite("B3-B3B durable reconciliation consumption", () => {
  it("persists MATCHED multi-source evidence and replays one generation idempotently", { timeout: 120000 }, async () => { const f = await fixture(); try { const first: ReconciliationResult = { ...matched(f), sources: ["OPEN_ORDERS", "ORDER_HISTORY"], observations: [...matched(f).observations, { ...matched(f).observations[0], source: "ORDER_HISTORY" }] }; const deps = { runKey: "same-generation", reconcile: (async () => first) as never }; const a = await consumeBingXSubmissionReconciliation(f.userId, f.uid, deps); const b = await consumeBingXSubmissionReconciliation(f.userId, f.uid, deps); assert.equal(a.status, "MATCHED"); assert.equal(b.durableRunId, a.durableRunId); const counts = await pool!.query("SELECT (SELECT count(*) FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1) runs,(SELECT count(*) FROM goodtrading_broker_objects WHERE broker_account_identity=$2) objects,(SELECT count(*) FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$2) aliases,(SELECT count(*) FROM goodtrading_broker_observation_snapshots WHERE broker_object_id IN (SELECT id FROM goodtrading_broker_objects WHERE broker_account_identity=$2)) snapshots", [f.attemptId, f.accountUid]); assert.deepEqual(counts.rows[0], { runs: "1", objects: "1", aliases: "2", snapshots: "2" }); const attempt = await pool!.query("SELECT transport_state FROM goodtrading_order_submission_attempts WHERE id=$1", [f.attemptId]); assert.equal(attempt.rows[0].transport_state, "RECONCILIATION_REQUIRED"); } finally { await cleanup(f); } });
  it("persists all non-match outcomes with hard safety flags", { timeout: 120000 }, async () => { for (const status of ["CONFLICT", "NO_MATCH_IN_OBSERVED_WINDOW", "UNRESOLVED"] as const) { const f = await fixture(); try { const result: ReconciliationResult = { status, logicalOrderUid: f.uid, brokerClientOrderId: f.client, sources: [], observations: [], sourceStatuses: status === "UNRESOLVED" ? { ...sourceStatuses, FILL_HISTORY: "failed" } : sourceStatuses, absenceProven: false, retryAuthorized: false, errorCodes: status === "UNRESOLVED" ? ["BINGX_TIMEOUT"] : undefined }; await consumeBingXSubmissionReconciliation(f.userId, f.uid, { runKey: `run-${status}`, reconcile: (async () => result) as never }); const row = await pool!.query("SELECT result,absence_proven,retry_authorized,source_error_codes,conflict_reasons FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1", [f.attemptId]); assert.equal(row.rows[0].result, status); assert.equal(row.rows[0].absence_proven, false); assert.equal(row.rows[0].retry_authorized, false); if (status === "UNRESOLVED") assert.deepEqual(row.rows[0].source_error_codes, ["BINGX_TIMEOUT"]); if (status === "CONFLICT") assert.deepEqual(row.rows[0].conflict_reasons, ["CORROBORATING_EVIDENCE_CONFLICT"]); const objects = await pool!.query("SELECT count(*)::int n FROM goodtrading_broker_objects WHERE broker_account_identity=$1", [f.accountUid]); assert.equal(objects.rows[0].n, 0); } finally { await cleanup(f); } } });
  it("converges concurrent same-key and different-key MATCHED workers", { timeout: 120000 }, async () => { const f = await fixture(); try { const result = matched(f); const same = () => consumeBingXSubmissionReconciliation(f.userId, f.uid, { runKey: "race-same", reconcile: (async () => result) as never }); await Promise.all([same(), same()]); const different = (key: string) => consumeBingXSubmissionReconciliation(f.userId, f.uid, { runKey: key, reconcile: (async () => result) as never }); await Promise.all([different("race-a"), different("race-b")]); const counts = await pool!.query("SELECT (SELECT count(*) FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1) runs,(SELECT count(*) FROM goodtrading_broker_objects WHERE broker_account_identity=$2) objects,(SELECT count(*) FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$2) aliases,(SELECT count(*) FROM goodtrading_broker_objects WHERE broker_account_identity=$2 AND attempt_id=$1) linked", [f.attemptId, f.accountUid]); assert.equal(Number(counts.rows[0].runs), 3); assert.equal(Number(counts.rows[0].objects), 1); assert.equal(Number(counts.rows[0].aliases), 2); assert.equal(Number(counts.rows[0].linked), 1); } finally { await cleanup(f); } });
  it("resumes a STARTED run after a crash before broker read", { timeout: 120000 }, async () => { const f = await fixture(); try { const started = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "crash-window", queriedSources: ["OPEN_ORDERS"] }); const result: ReconciliationResult = { status: "NO_MATCH_IN_OBSERVED_WINDOW", logicalOrderUid: f.uid, brokerClientOrderId: f.client, sources: [], observations: [], sourceStatuses: sourceStatuses, absenceProven: false, retryAuthorized: false }; const consumed = await consumeBingXSubmissionReconciliation(f.userId, f.uid, { runKey: "crash-window", reconcile: (async () => result) as never }); assert.equal(consumed.durableRunId, started.id); const count = await pool!.query("SELECT count(*)::int n FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1 AND run_key=$2", [f.attemptId, "crash-window"]); assert.equal(count.rows[0].n, 1); } finally { await cleanup(f); } });
  it("does not rewrite a completed run to another result", { timeout: 120000 }, async () => { const f = await fixture(); try { const result = matched(f); await consumeBingXSubmissionReconciliation(f.userId, f.uid, { runKey: "immutable", reconcile: (async () => result) as never }); const existing = await getReconciliationRunByAttemptAndKey(f.attemptId, "immutable"); assert.equal(existing?.result, "MATCHED"); const second = await consumeBingXSubmissionReconciliation(f.userId, f.uid, { runKey: "immutable", reconcile: async () => { throw new Error("READ_MUST_NOT_REPEAT"); } }); assert.equal(second.status, "MATCHED"); } finally { await cleanup(f); } });
});
