import { pool } from "../../../db";
import type { BingXBookTickerBboEvent } from "./bingxBookTicker";
import { validateDurableBingXBboEvent, type DurableBingXBboEvent } from "./bingxBboHistory";

function database() { if (!pool) throw new Error("DATABASE_UNAVAILABLE"); return pool; }
function rowToEvent(row: Record<string, unknown>): DurableBingXBboEvent { return { id:String(row.id), canonicalMarket:{venue:"BINGX",marketType:"Perpetual",symbol:"BTC-USDT"}, venue:"BINGX", product:"Perpetual", nativeSymbol:"BTC-USDT", marketSource:"BINGX_BOOK_TICKER", marketSourceTimestampMs:Number(row.market_source_timestamp_ms), observedAt:new Date(row.observed_at as string), sourceAgeAtObservationMs:Number(row.source_age_at_observation_ms), sourceAgeDiagnostic:Number(row.source_age_at_observation_ms)<0?"SOURCE_TIMESTAMP_AFTER_OBSERVED_AT":null, bestBid:String(row.best_bid), bestAsk:String(row.best_ask), bestBidQuantity:String(row.best_bid_quantity), bestAskQuantity:String(row.best_ask_quantity), providerSequence:row.provider_update_id==null?null:String(row.provider_update_id), provenance:{source:"BINGX_PUBLIC_WS",endpoint:"wss://open-api-swap.bingx.com/swap-market",subscription:"BTC-USDT@bookTicker"} }; }
function params(event: DurableBingXBboEvent): unknown[] { return [event.id,"BINGX","Perpetual","BTC-USDT","BINGX_BOOK_TICKER",event.marketSourceTimestampMs,event.observedAt,event.bestBid,event.bestAsk,event.bestBidQuantity,event.bestAskQuantity,event.providerSequence,event.sourceAgeAtObservationMs]; }
export async function insertBingXBboEvent(event: BingXBookTickerBboEvent): Promise<DurableBingXBboEvent> { const checked=validateDurableBingXBboEvent(event); if(!checked.ok)throw new Error(checked.code); const e=checked.event; const r=await database().query(`INSERT INTO goodtrading_market_bbo_events (id,venue,market_type,native_symbol,market_source,market_source_timestamp_ms,observed_at,best_bid,best_ask,best_bid_quantity,best_ask_quantity,provider_update_id,source_age_at_observation_ms) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,params(e)); return rowToEvent(r.rows[0]); }
export async function getLatestBingXBboEvent(): Promise<DurableBingXBboEvent|null> { const r=await database().query(`SELECT * FROM goodtrading_market_bbo_events WHERE venue='BINGX' AND market_type='Perpetual' AND native_symbol='BTC-USDT' AND market_source='BINGX_BOOK_TICKER' ORDER BY market_source_timestamp_ms DESC, observed_at DESC, id DESC LIMIT 1`); return r.rows[0]?rowToEvent(r.rows[0]):null; }
export async function getBingXBboAtOrBefore(sourceTimestampMs: number): Promise<DurableBingXBboEvent|null> { if(!Number.isSafeInteger(sourceTimestampMs)||sourceTimestampMs<=0)throw new Error("INVALID_TARGET_TIMESTAMP"); const r=await database().query(`SELECT * FROM goodtrading_market_bbo_events WHERE venue='BINGX' AND market_type='Perpetual' AND native_symbol='BTC-USDT' AND market_source='BINGX_BOOK_TICKER' AND market_source_timestamp_ms <= $1 ORDER BY market_source_timestamp_ms DESC, observed_at DESC, id DESC LIMIT 1`,[sourceTimestampMs]); return r.rows[0]?rowToEvent(r.rows[0]):null; }
export async function listBingXBboEvents(startMs: number, endMs: number): Promise<DurableBingXBboEvent[]> { const r=await database().query(`SELECT * FROM goodtrading_market_bbo_events WHERE venue='BINGX' AND market_type='Perpetual' AND native_symbol='BTC-USDT' AND market_source='BINGX_BOOK_TICKER' AND market_source_timestamp_ms >= $1 AND market_source_timestamp_ms <= $2 ORDER BY market_source_timestamp_ms ASC, observed_at ASC, id ASC`,[startMs,endMs]); return r.rows.map(rowToEvent); }
