import { z } from "zod";
import type { ResearchBudget, ResearchHypothesis, ResearchPlan, StrategyProposal, MentorAnswer } from "./types";

export const researchBudgetSchema = z.object({ maxModelCalls: z.number().int().positive().max(20), maxToolCalls: z.number().int().positive().max(100), maxExperiments: z.number().int().nonnegative().max(20), maxVariants: z.number().int().nonnegative().max(20), maxIterations: z.number().int().positive().max(20) });
export const citationRefSchema = z.object({ id: z.string().min(1), kind: z.enum(["K", "E", "T", "D"]), label: z.string(), sourceId: z.string() });
export const researchHypothesisSchema = z.object({ hypothesisId: z.string().min(1), statement: z.string().min(1), rationale: z.string().min(1), requiredEvidence: z.array(z.string()), requiredCapabilities: z.array(z.string()), testable: z.boolean(), strategyCompatible: z.boolean(), assumptions: z.array(z.string()), invalidatingEvidence: z.array(z.string()), status: z.enum(["PROPOSED", "TESTED", "SUPPORTED", "INVALIDATED", "NOT_TESTABLE_WITH_CURRENT_FEATURES"]), citations: z.array(citationRefSchema) });
export const researchPlanSchema = z.object({ question: z.string().min(1), hypothesisIds: z.array(z.string()), datasetRequirements: z.array(z.string()), features: z.array(z.string()), strategyMapping: z.array(z.string()), metrics: z.array(z.string()), invalidationCriteria: z.array(z.string()), budget: researchBudgetSchema, citations: z.array(citationRefSchema) });
export const strategyProposalSchema = z.object({ hypothesisId: z.string().min(1), strategy: z.record(z.any()), explanation: z.string(), citations: z.array(citationRefSchema) });
export const mentorAnswerSchema = z.object({ answer: z.string().min(1), classification: z.array(z.enum(["FACT", "OBSERVATION", "DERIVATION", "HYPOTHESIS", "INTERPRETATION", "EXPERIMENT_RESULT", "RECOMMENDATION_FOR_RESEARCH"])), citations: z.array(citationRefSchema), limitations: z.array(z.string()), provider: z.object({ id: z.string(), model: z.string().optional(), mocked: z.boolean() }) });
export const researchQuestionSchema = z.object({ question: z.string().min(1).max(2000), budget: researchBudgetSchema.optional(), dataset: z.any().optional(), config: z.any().optional() });
export function parseStructured<T>(schema: z.ZodType<T>, value: unknown): T { const result = schema.safeParse(value); if (!result.success) throw new Error(`INVALID_STRUCTURED_OUTPUT:${result.error.issues.map((x) => x.path.join(".") + ":" + x.message).join(";")}`); return result.data; }
export type { ResearchBudget, ResearchHypothesis, ResearchPlan, StrategyProposal, MentorAnswer };
