import { ke, type GoodTradingKnowledgeEntry } from "./types";

/** Foundational principles — retrieval must prefer these over heuristics when relevant. */
export const CONSTITUTION_ENTRIES: readonly GoodTradingKnowledgeEntry[] = [
  ke({
    id: "gt_const_context_over_signal",
    title: "Contexto antes que señal",
    category: "constitution",
    kind: "PRINCIPLE",
    concepts: ["contexto", "señal", "context", "signal"],
    aliases: ["context first", "no señales aisladas"],
    statement: "Ninguna métrica aislada justifica una decisión; el contexto estructura la lectura.",
    explanation:
      "Gamma, liquidez, delta o OI solo adquieren sentido dentro de estructura, ubicación relativa y plan de riesgo. Una 'señal' sin marco es ruido educativamente peligroso.",
    prohibitedInterpretations: [
      "Una sola métrica confirma entrada",
      "El indicador reemplaza el plan",
    ],
    examples: [
      "CVD alcista cerca de una zona sin estructura clara no es permiso automático de compra.",
    ],
    relatedEntryIds: ["gt_const_hypothesis_not_certainty", "gt_risk_invalidation_first"],
  }),
  ke({
    id: "gt_const_hypothesis_not_certainty",
    title: "Hipótesis, no certeza",
    category: "constitution",
    kind: "PRINCIPLE",
    concepts: ["hipótesis", "certeza", "hypothesis"],
    aliases: ["no certezas", "probabilistic framing"],
    statement: "Toda lectura de mercado es una hipótesis revisable, nunca una verdad cerrada.",
    explanation:
      "Incluso con múltiples confirmaciones, el proceso exige invalidación explícita. El lenguaje de certeza ('va a', 'seguro') degrada el pensamiento probabilístico.",
    prohibitedInterpretations: ["El setup garantiza el resultado", "Confirmar = certeza"],
    examples: ["Decir 'hipótesis de absorción si persiste pasivo' en lugar de 'hay absorción segura'."],
    relatedEntryIds: ["gt_const_invalidation_required", "gt_of_absorption_central"],
  }),
  ke({
    id: "gt_const_invalidation_required",
    title: "Invalidación obligatoria",
    category: "constitution",
    kind: "RULE",
    concepts: ["invalidación", "invalidation"],
    aliases: ["stop conceptual", "condiciones de salida"],
    statement: "Sin invalidación objetiva no hay tesis operable, solo narrativa.",
    explanation:
      "La invalidación define cuándo la hipótesis queda cancelada. Debe ser medible (nivel, secuencia, pérdida de estructura) antes de discutir R:R o tamaño.",
    prohibitedInterpretations: ["Invalidación opcional si el edge es fuerte", "Mover invalidación por esperanza"],
    examples: ["Tesis de reclaim: invalidación si cierra/acepta de nuevo bajo el nivel barrido."],
    relatedEntryIds: ["gt_risk_invalidation_first", "gt_const_confirmation_is_evidence"],
  }),
  ke({
    id: "gt_const_confirmation_is_evidence",
    title: "Confirmación es evidencia adicional",
    category: "constitution",
    kind: "RULE",
    concepts: ["confirmación", "confirmation"],
    aliases: ["evidence stacking"],
    statement: "Confirmación = evidencia alineada extra; no convierte una idea en mandato.",
    explanation:
      "Apilar confirmaciones reduce incertidumbre relativa, pero no elimina riesgo ni autoriza tamaño irresponsable.",
    prohibitedInterpretations: ["Más confirmaciones = entrada obligatoria"],
    examples: ["Reclaim + pasivo que sostiene + delta que deja de empujar en contra."],
    relatedEntryIds: ["gt_const_invalidation_required", "gt_liq_sweep_reclaim"],
  }),
  ke({
    id: "gt_const_no_live_advice",
    title: "Sin consejo personalizado ni mercado en vivo",
    category: "constitution",
    kind: "RULE",
    concepts: ["educativo", "asesoramiento", "live market", "mercado en vivo"],
    aliases: ["no financial advice", "no live analysis"],
    statement: "El Modo Mentor educa metodología; no analiza el mercado actual ni recomienda compras/ventas.",
    explanation:
      "Preguntas sobre 'qué comprar hoy' o 'analiza BTC ahora' deben redirigirse a marcos educativos y límites del sistema.",
    prohibitedInterpretations: [
      "El mentor ve tu Bookmap/DOM",
      "La respuesta es una orden operativa",
    ],
    examples: ["Ante 'mejor crypto hoy': explicar que no hay lectura en vivo y ofrecer marco de evaluación educativa."],
    relatedEntryIds: ["gt_teach_insufficient_info", "gt_const_risk_over_prediction"],
  }),
  ke({
    id: "gt_const_risk_over_prediction",
    title: "Riesgo sobre predicción",
    category: "constitution",
    kind: "PRINCIPLE",
    concepts: ["riesgo", "risk", "predicción"],
    aliases: ["risk first"],
    statement: "Definir qué se está dispuesto a perder precede a proyectar a dónde irá el precio.",
    explanation:
      "La metodología prioriza supervivencia y disciplina. Predicción sin control de daño es entretenimiento, no proceso.",
    prohibitedInterpretations: ["Si la predicción es buena el riesgo no importa"],
    examples: ["Antes de discutir un fade a un wall: tamaño máximo y condición de aborto."],
    relatedEntryIds: ["gt_risk_position_sizing_context", "gt_risk_invalidation_first"],
  }),
  ke({
    id: "gt_const_levels_are_references",
    title: "Niveles son referencias, no órdenes",
    category: "constitution",
    kind: "PRINCIPLE",
    concepts: ["niveles", "levels", "referencia"],
    aliases: ["levels as context"],
    statement: "Walls, flips y pivots orientan la lectura; no son botones de compra/venta.",
    explanation:
      "Un nivel relevante organiza escenarios (aceptación, rechazo, barrido). Operar el nivel 'porque está dibujado' es anti-patrón.",
    prohibitedInterpretations: ["Tocar el nivel = reversión", "Wall = soporte garantizado"],
    examples: ["Call wall como zona de posible fricción, no como short automático."],
    relatedEntryIds: ["gt_gamma_walls_reference", "gt_liq_wall_not_reversal"],
  }),
  ke({
    id: "gt_const_multi_lens",
    title: "Lectura multi-lente",
    category: "constitution",
    kind: "PRINCIPLE",
    concepts: ["multi lente", "gamma", "liquidez", "order flow", "integración"],
    aliases: ["gamma liquidity orderflow", "combined reading"],
    statement: "Gamma, liquidez y order flow se leen juntos; una lente sola sesga la conclusión.",
    explanation:
      "Un régimen de gamma sugiere comportamientos esperados; la liquidez muestra dónde hay fricción; el order flow valida o niega la aceptación. La integración es el método.",
    prohibitedInterpretations: ["Solo gamma basta", "Solo DOM basta"],
    examples: ["Short gamma + barrido de liquidez + fallo de continuación = escenario educativo de volatilidad."],
    relatedEntryIds: ["gt_cross_gamma_liquidity", "gt_cross_liquidity_orderflow"],
  }),
  ke({
    id: "gt_const_process_over_outcome",
    title: "Proceso sobre resultado",
    category: "constitution",
    kind: "PRINCIPLE",
    concepts: ["proceso", "resultado", "disciplina"],
    aliases: ["process over PnL"],
    statement: "Una buena decisión puede perder; una mala puede ganar. Se evalúa el proceso.",
    explanation:
      "El resultado corto no valida el método. El mentor enseña checklists y disciplina, no scorekeeping de suerte.",
    prohibitedInterpretations: ["Si ganó, el proceso era correcto"],
    examples: ["Trade con invalidación respetada y pérdida limitada sigue siendo proceso sano."],
    relatedEntryIds: ["gt_risk_invalidation_first", "gt_teach_common_traps"],
  }),
  ke({
    id: "gt_const_no_universal_percent",
    title: "Sin porcentajes universales",
    category: "constitution",
    kind: "RULE",
    concepts: ["porcentaje", "risk percent", "2%", "sizing universal"],
    aliases: ["no fixed risk percent"],
    statement: "No existe un % de riesgo universal correcto para todos los contextos y operadores.",
    explanation:
      "El tamaño depende de volatilidad, liquidez, correlación, drawdown y psicología. Recetas fijas ('siempre 2%') son heurísticas frágiles si se absolutizan.",
    prohibitedInterpretations: ["Siempre arriesgá X% en cada trade"],
    examples: ["En alta volatilidad el mismo % nominal puede ser sobreexposición."],
    relatedEntryIds: ["gt_risk_position_sizing_context", "gt_exec_no_fixed_rr"],
  }),
  ke({
    id: "gt_const_language_discipline",
    title: "Disciplina de lenguaje",
    category: "constitution",
    kind: "RULE",
    concepts: ["lenguaje", "comunicación", "certeza"],
    aliases: ["careful wording"],
    statement: "El lenguaje debe distinguir hecho, regla, heurística y ejemplo.",
    explanation:
      "Confundir una heurística con una regla produce sobreconfianza. El knowledge model etiqueta kinds para forzar esa claridad.",
    prohibitedInterpretations: ["Heurística = ley del mercado"],
    examples: ["'Suele' para heurísticas; 'debe' solo para reglas de proceso (invalidación, riesgo)."],
    relatedEntryIds: ["gt_teach_kinds_taxonomy", "gt_const_hypothesis_not_certainty"],
  }),
  ke({
    id: "gt_const_insufficient_info",
    title: "Reconocer información insuficiente",
    category: "constitution",
    kind: "RULE",
    concepts: ["información insuficiente", "insufficient", "cobertura limitada"],
    aliases: ["know when not to answer", "limited coverage"],
    statement: "Si falta evidencia o cobertura metodológica, se declara límite; no se inventa.",
    explanation:
      "El mentor prefiere cobertura limitada explícita a relleno genérico o análisis falso del 'ahora'.",
    prohibitedInterpretations: ["Completar con conjeturas de mercado actual"],
    examples: ["Pregunta fuera de metodología → warning de cobertura + conceptos sí cubiertos."],
    relatedEntryIds: ["gt_teach_insufficient_info", "gt_const_no_live_advice"],
  }),
];
