import { ke, type GoodTradingKnowledgeEntry } from "./types";

export const GAMMA_ENTRIES: readonly GoodTradingKnowledgeEntry[] = [
  ke({
    id: "gt_gamma_definition",
    title: "Qué es Gamma",
    category: "gamma",
    kind: "DEFINITION",
    concepts: ["gamma", "greeks", "convexity"],
    aliases: ["opción gamma"],
    statement: "Gamma mide cómo cambia el delta de una opción ante movimientos del subyacente.",
    explanation:
      "En desks, la gamma agregada informa presión potencial de cobertura de dealers. No es un botón de entrada.",
    prohibitedInterpretations: ["Gamma alta = comprar", "Gamma negativa = vender"],
    relatedEntryIds: ["gt_gamma_pos_neg_hypothesis", "gt_const_context_over_signal"],
  }),
  ke({
    id: "gt_gamma_pos_neg_hypothesis",
    title: "Gamma positiva/negativa como hipótesis",
    category: "gamma",
    kind: "RULE",
    concepts: ["long gamma", "short gamma", "gamma positiva", "gamma negativa", "positive gamma", "negative gamma"],
    aliases: ["gamma regime hypothesis"],
    statement:
      "Long/short gamma son hipótesis de régimen sobre comportamiento esperado de cobertura, no certezas direccionales.",
    explanation:
      "Short gamma se asocia a potencial de amplificar movimientos; long gamma a amortiguar. El precio puede violar la expectativa.",
    prohibitedInterpretations: [
      "Gamma negativa = vender",
      "Gamma positiva = comprar",
      "El régimen garantiza el path",
    ],
    relatedEntryIds: ["gt_gamma_definition", "gt_of_cross_with_gamma", "gt_const_hypothesis_not_certainty"],
  }),
  ke({
    id: "gt_gamma_flip_zone",
    title: "Flip como zona",
    category: "gamma",
    kind: "RULE",
    concepts: ["gamma flip", "global flip", "flip", "local flip"],
    aliases: ["flip zone", "punto de flip"],
    statement: "El flip se trata como zona/régimen de transición, no como tick mágico exacto.",
    explanation:
      "Modelos discretizan un número; la práctica educativa usa banda, contexto y confirmación de acceptance alrededor del área.",
    prohibitedInterpretations: ["Cruzar el flip = señal market"],
    relatedEntryIds: ["gt_gamma_global_vs_local", "gt_setup_flip_transition", "gt_const_levels_are_references"],
  }),
  ke({
    id: "gt_gamma_global_vs_local",
    title: "Global Flip vs Local Flip",
    category: "gamma",
    kind: "DEFINITION",
    concepts: ["global flip", "local flip"],
    aliases: ["flip global", "flip local"],
    statement: "Global Flip describe régimen agregado más amplio; Local Flip un pivote más cercano/contextual.",
    explanation:
      "Útiles para multi-escala. Confundir escalas genera lecturas contradictorias.",
    relatedEntryIds: ["gt_gamma_flip_zone", "gt_gamma_dealer_pivot"],
  }),
  ke({
    id: "gt_gamma_dealer_pivot",
    title: "Dealer Pivot",
    category: "gamma",
    kind: "DEFINITION",
    concepts: ["dealer pivot", "pivot", "dealers"],
    aliases: ["pivote de dealers"],
    statement: "Dealer Pivot es referencia alrededor de la cual puede cambiar el comportamiento de cobertura.",
    explanation:
      "Se interpreta con walls y flip, nunca solo. No sustituye gestión de riesgo.",
    relatedEntryIds: ["gt_gamma_walls_reference", "gt_gamma_flip_zone"],
  }),
  ke({
    id: "gt_gamma_walls_reference",
    title: "Call/Put Wall como referencia",
    category: "gamma",
    kind: "RULE",
    concepts: ["call wall", "put wall", "walls"],
    aliases: ["gamma wall", "option wall"],
    statement: "Call/Put walls son referencias de concentración de exposición, no órdenes de trading.",
    explanation:
      "Pueden actuar como imanes o zonas de fricción. Romperlas o rechazarlas son escenarios, no mandatos.",
    prohibitedInterpretations: ["Wall = reversión segura", "Shortear todo call wall"],
    relatedEntryIds: ["gt_liq_wall_not_reversal", "gt_const_levels_are_references", "gt_oi_walls_link"],
  }),
  ke({
    id: "gt_gamma_pinning_heuristic",
    title: "Pinning (heurística)",
    category: "gamma",
    kind: "HEURISTIC",
    concepts: ["pinning", "pin risk", "magnet gamma"],
    aliases: ["price pinning"],
    statement: "Cerca de expiración, concentraciones pueden favorecer pinning relativo; no es ley.",
    explanation:
      "Heurística de evento/expiración. Fuera de contexto pierde poder y puede confundir con liquidez spot.",
    prohibitedInterpretations: ["Siempre pinea al strike"],
    relatedEntryIds: ["gt_gamma_walls_reference", "gt_oi_near_expiry"],
  }),
  ke({
    id: "gt_gamma_vanna_charm_context",
    title: "Vanna/Charm como contexto",
    category: "gamma",
    kind: "HEURISTIC",
    concepts: ["vanna", "charm", "greeks higher order"],
    aliases: ["vanna charm"],
    statement: "Vanna/Charm añaden matices de sensibilidad a vol y tiempo; no reemplazan estructura.",
    explanation:
      "Útiles en desks avanzados. En Mentor se mencionan como capas secundarias, no como señales.",
    relatedEntryIds: ["gt_gamma_definition", "gt_const_multi_lens"],
  }),
  ke({
    id: "gt_gamma_hedging_pressure",
    title: "Presión de hedging",
    category: "gamma",
    kind: "HEURISTIC",
    concepts: ["hedging", "cobertura", "dealer hedging"],
    aliases: ["hedge pressure"],
    statement: "La cobertura de dealers puede amplificar o amortiguar; es mecanismo hipotético, no timing exacto.",
    explanation:
      "Evitar relatos mecanicistas ('los dealers van a comprar aquí sí o sí').",
    prohibitedInterpretations: ["Los dealers garantizan el bounce"],
    relatedEntryIds: ["gt_gamma_pos_neg_hypothesis", "gt_const_hypothesis_not_certainty"],
  }),
  ke({
    id: "gt_gamma_not_spot_liquidity",
    title: "Gamma ≠ liquidez spot",
    category: "gamma",
    kind: "RULE",
    concepts: ["gamma vs liquidez", "gamma liquidez"],
    aliases: ["gamma is not book"],
    statement: "Mapas de gamma no son el order book spot; no sustituyen lectura de liquidez.",
    explanation:
      "Integrar ambas lentes: gamma sugiere régimen; liquidez muestra fricción real de ejecución.",
    relatedEntryIds: ["gt_cross_gamma_liquidity", "gt_liq_definition"],
  }),
  ke({
    id: "gt_gamma_anti_binary",
    title: "Anti-patrón: gamma binaria",
    category: "gamma",
    kind: "ANTI_PATTERN",
    concepts: ["gamma binaria", "binary gamma"],
    aliases: ["long short absolutism"],
    statement: "Tratar long/short gamma como verdad binaria absoluta es anti-patrón.",
    explanation:
      "Los perfiles son estimaciones con supuestos de modelo, vencimientos y datos. Exigen humildad.",
    relatedEntryIds: ["gt_gamma_pos_neg_hypothesis", "gt_const_language_discipline"],
  }),
  ke({
    id: "gt_gamma_example_flip_transition",
    title: "Ejemplo: transición en flip",
    category: "gamma",
    kind: "EXAMPLE",
    concepts: ["ejemplo flip"],
    aliases: ["caso flip"],
    statement: "Ejemplo educativo: precio acepta sobre zona de flip y cambia el juego de mean-reversion vs expansión.",
    explanation:
      "Se discute como cambio de sesgo de régimen hipotético, no como 'comprar el cruce'.",
    examples: ["Acceptance sobre flip + order flow de iniciativa → hipótesis de régimen más expansivo."],
    relatedEntryIds: ["gt_gamma_flip_zone", "gt_setup_flip_transition"],
  }),
  ke({
    id: "gt_gamma_distance_context",
    title: "Distancia al flip/walls",
    category: "gamma",
    kind: "HEURISTIC",
    concepts: ["distancia al flip", "distance to flip", "distance to wall"],
    aliases: ["proximity gamma"],
    statement: "La proximidad a flip/walls cambia la relevancia relativa de la referencia.",
    explanation:
      "Lejos, el nivel es mapa; cerca, organiza escenarios. Nunca convierte el nivel en orden.",
    relatedEntryIds: ["gt_gamma_flip_zone", "gt_gamma_walls_reference"],
  }),
  ke({
    id: "gt_gamma_model_limits",
    title: "Límites de modelos de gamma",
    category: "gamma",
    kind: "RULE",
    concepts: ["modelo", "gex", "limites modelo"],
    aliases: ["model risk gamma"],
    statement: "Todo mapa de gamma hereda supuestos; discrepancia entre fuentes es esperable.",
    explanation:
      "El mentor no pelea por un número 'verdadero'; enseña a usar el mapa como marco.",
    relatedEntryIds: ["gt_const_insufficient_info", "gt_gamma_anti_binary"],
  }),
  ke({
    id: "gt_gamma_oi_link",
    title: "Gamma y OI se interpretan juntos",
    category: "gamma",
    kind: "HEURISTIC",
    concepts: ["gamma oi", "gamma open interest"],
    aliases: ["gex and oi"],
    statement: "Concentraciones de OI informan dónde la gamma puede importar más.",
    explanation:
      "OI sin greeks es incompleto; greeks sin OI también. Cross-reading básico del método.",
    relatedEntryIds: ["gt_oi_definition", "gt_oi_walls_link", "gt_cross_gamma_oi"],
  }),
];
