import { ke, type GoodTradingKnowledgeEntry } from "./types";

export const GLOSSARY_ENTRIES: readonly GoodTradingKnowledgeEntry[] = [
  ke({
    id: "gt_glos_gex",
    title: "GEX (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["gex", "gamma exposure"],
    aliases: ["gamma exposure"],
    statement: "GEX suele referirse a estimaciones de exposición gamma agregada; es modelo, no verdad de mercado.",
    explanation: "Usar como mapa. Ver límites de modelo.",
    relatedEntryIds: ["gt_gamma_model_limits", "gt_gamma_definition"],
  }),
  ke({
    id: "gt_glos_spot",
    title: "Spot (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["spot", "precio spot"],
    aliases: ["cash price"],
    statement: "Spot es el precio del subyacente al contado/referencia usada por el terminal.",
    explanation: "Anclas de distancia a flip/walls se miden respecto a spot (cuando está disponible al operador).",
    relatedEntryIds: ["gt_gamma_distance_context"],
  }),
  ke({
    id: "gt_glos_acceptance",
    title: "Acceptance (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["acceptance"],
    aliases: ["aceptación de precio"],
    statement: "Acceptance: el mercado opera y sostiene un área de precios.",
    explanation: "Ver regla de acceptance/rejection en order flow.",
    relatedEntryIds: ["gt_of_acceptance_rejection"],
  }),
  ke({
    id: "gt_glos_rejection",
    title: "Rejection (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["rejection"],
    aliases: ["rechazo de precio"],
    statement: "Rejection: fallo en sostener/aceptar un área tras intentar operar allí.",
    explanation: "Complemento de acceptance.",
    relatedEntryIds: ["gt_of_acceptance_rejection"],
  }),
  ke({
    id: "gt_glos_rr",
    title: "R:R (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["r:r", "risk reward"],
    aliases: ["reward to risk"],
    statement: "R:R compara recompensa potencial con riesgo hasta invalidación.",
    explanation: "Sin invalidación no hay R:R real.",
    relatedEntryIds: ["gt_exec_no_fixed_rr", "gt_risk_define_r"],
  }),
  ke({
    id: "gt_glos_edge",
    title: "Edge (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["edge", "ventaja"],
    aliases: ["expectancy"],
    statement: "Edge es ventaja estadística hipotética de un proceso — no una racha de wins.",
    explanation: "Se evalúa en muestras y disciplina, no en un trade.",
    relatedEntryIds: ["gt_const_process_over_outcome"],
  }),
  ke({
    id: "gt_glos_htf_ltf",
    title: "HTF / LTF (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["htf", "ltf", "timeframe"],
    aliases: ["higher timeframe", "lower timeframe"],
    statement: "HTF/LTF distinguen marcos temporales; mezclarlos sin declararlo genera ruido.",
    explanation: "Flip global vs local es un ejemplo de multi-escala.",
    relatedEntryIds: ["gt_gamma_global_vs_local", "gt_dc_window_matters"],
  }),
  ke({
    id: "gt_glos_auction",
    title: "Auction (glosario)",
    category: "glossary",
    kind: "DEFINITION",
    concepts: ["auction", "subasta"],
    aliases: ["auction market"],
    statement: "Metáfora de subasta: el mercado busca acceptance de precio vía iniciativa y respuesta.",
    explanation: "Base conceptual de failed auction / unfinished business.",
    relatedEntryIds: ["gt_of_failed_auction", "gt_of_initiative_vs_responsive"],
  }),
];
