import { ke, type GoodTradingKnowledgeEntry } from "./types";

export const LIQUIDITY_ENTRIES: readonly GoodTradingKnowledgeEntry[] = [
  ke({
    id: "gt_liq_definition",
    title: "Qué es liquidez",
    category: "liquidity",
    kind: "DEFINITION",
    concepts: ["liquidez", "liquidity"],
    aliases: ["depth", "profundidad"],
    statement: "Liquidez es la capacidad del libro de absorber tamaño con impacto acotado.",
    explanation:
      "No es solo 'mucho volumen histórico': es oferta/demanda pasiva y agresiva interactuando en el tiempo. Una pared visible puede desaparecer.",
    prohibitedInterpretations: ["Liquidez visible = soporte eterno"],
    examples: ["Gran bid que se retira al acercarse el precio (pulling)."],
    relatedEntryIds: ["gt_liq_wall_not_reversal", "gt_liq_persistence"],
  }),
  ke({
    id: "gt_liq_wall_not_reversal",
    title: "Wall ≠ reversión",
    category: "liquidity",
    kind: "RULE",
    concepts: ["liquidity wall", "muro de liquidez", "wall", "walls"],
    aliases: ["pared de liquidez", "liquidity wall"],
    statement: "Una wall de liquidez es concentración pasiva; no confirma por sí sola una reversión.",
    explanation:
      "Puede frenar, atraer (magnet), ser barrida o retirada. Tratarla como reversión garantizada es anti-patrón central.",
    prohibitedInterpretations: [
      "Wall confirma reversión",
      "Tocar el muro = short/long automático",
    ],
    examples: ["Ask wall grande que se pulla y el precio acelera a través."],
    relatedEntryIds: ["gt_liq_persistence", "gt_liq_pulling", "gt_const_levels_are_references"],
  }),
  ke({
    id: "gt_liq_persistence",
    title: "Persistencia de liquidez",
    category: "liquidity",
    kind: "HEURISTIC",
    concepts: ["persistencia", "persistence", "liquidity persistence"],
    aliases: ["liquidez que se mantiene"],
    statement: "La liquidez que persiste al interactuar con el precio es más informativa que la que solo aparece lejos.",
    explanation:
      "Persistencia sugiere intención relativa de absorber; ausencia de persistencia sugiere spoof/pull o decoración del libro.",
    conditions: ["Interacción real con agresores", "Tiempo suficiente en el nivel"],
    confirmations: ["Reposición de tamaño tras hits parciales"],
    invalidations: ["Retiro sistemático al acercarse el precio"],
    relatedEntryIds: ["gt_liq_pulling", "gt_liq_spoofing_hypothesis"],
  }),
  ke({
    id: "gt_liq_pulling",
    title: "Pulling",
    category: "liquidity",
    kind: "DEFINITION",
    concepts: ["pulling", "retiro de liquidez"],
    aliases: ["pull", "liquidez que se retira"],
    statement: "Pulling es el retiro rápido de liquidez pasiva antes o durante la interacción.",
    explanation:
      "Cambia el mapa de fricción. No implica por sí solo dirección futura; implica que el tamaño visible no era compromiso estable.",
    prohibitedInterpretations: ["Pulling = siempre manipulación ilegal"],
    examples: ["Bids grandes desaparecen un tick antes del trade agresivo."],
    relatedEntryIds: ["gt_liq_spoofing_hypothesis", "gt_liq_stacking"],
  }),
  ke({
    id: "gt_liq_stacking",
    title: "Stacking",
    category: "liquidity",
    kind: "DEFINITION",
    concepts: ["stacking", "apilar liquidez"],
    aliases: ["stack", "apilado"],
    statement: "Stacking es concentrar o reponer tamaño pasivo en un nivel o banda.",
    explanation:
      "Puede ser defensa genuina, imán, o preparación de engaño. Se evalúa con persistencia e interacción, no solo con tamaño inicial.",
    relatedEntryIds: ["gt_liq_persistence", "gt_liq_spoofing_hypothesis"],
  }),
  ke({
    id: "gt_liq_spoofing_hypothesis",
    title: "Spoofing como hipótesis",
    category: "liquidity",
    kind: "RULE",
    concepts: ["spoofing", "spoof"],
    aliases: ["engaño de libro"],
    statement: "Spoofing es una hipótesis sobre intención engañosa; no se declara solo por tamaño visible.",
    explanation:
      "Requiere patrón de aparición/retiro sin voluntad de ejecutarse. El mentor evita acusaciones absolutas y enseña criterios de evidencia.",
    prohibitedInterpretations: ["Tamaño grande = spoofing", "Spoofing siempre detectable a ojo"],
    confirmations: ["Retiros repetidos sin fills materiales", "Patrón sincronizado con movimientos"],
    invalidations: ["El tamaño se ejecuta de forma consistente"],
    relatedEntryIds: ["gt_liq_pulling", "gt_liq_stacking", "gt_of_absorption_central"],
  }),
  ke({
    id: "gt_liq_sweep",
    title: "Liquidity sweep",
    category: "liquidity",
    kind: "DEFINITION",
    concepts: ["sweep", "liquidity sweep", "barrido"],
    aliases: ["barrido de liquidez"],
    statement: "Un sweep barre liquidez más allá de un nivel relevante.",
    explanation:
      "Puede ser caza de stops, continuidad agresiva o precursor de reclaim. El sweep solo no define el trade.",
    prohibitedInterpretations: ["Todo sweep revierte"],
    relatedEntryIds: ["gt_liq_sweep_reclaim", "gt_setup_sweep_reclaim"],
  }),
  ke({
    id: "gt_liq_sweep_reclaim",
    title: "Sweep + reclaim",
    category: "liquidity",
    kind: "RULE",
    concepts: ["reclaim", "sweep reclaim", "recuperación de nivel"],
    aliases: ["barrido y recuperación"],
    statement: "Sweep seguido de reclaim es una secuencia educativa: barrido + recuperación/aceptación del nivel.",
    explanation:
      "El valor está en la secuencia completa y sus invalidaciones, no en el barrido aislado.",
    confirmations: ["Recuperación del nivel", "Fallo de continuación agresiva"],
    invalidations: ["Aceptación sostenida más allá del barrido"],
    relatedEntryIds: ["gt_liq_sweep", "gt_setup_sweep_reclaim", "gt_const_confirmation_is_evidence"],
  }),
  ke({
    id: "gt_liq_magnet",
    title: "Liquidez como imán",
    category: "liquidity",
    kind: "HEURISTIC",
    concepts: ["imán", "magnet", "atracción de liquidez"],
    aliases: ["liquidity magnet"],
    statement: "Concentraciones de liquidez pueden atraer precio antes de decidir aceptación o rechazo.",
    explanation:
      "Heurística: el precio a menudo 'visita' pools. No implica que revierta al llegar.",
    prohibitedInterpretations: ["El imán garantiza bounce"],
    relatedEntryIds: ["gt_liq_wall_not_reversal", "gt_gamma_walls_reference"],
  }),
  ke({
    id: "gt_liq_thin_book",
    title: "Libro fino y aceleración",
    category: "liquidity",
    kind: "HEURISTIC",
    concepts: ["thin book", "libro fino", "air pocket"],
    aliases: ["poca liquidez"],
    statement: "Libros finos facilitan aceleraciones y gaps de microestructura.",
    explanation:
      "En thin liquidity, el mismo tamaño agresivo mueve más. El riesgo de slippage conceptual aumenta.",
    risks: ["Sobreinterpretar un spike en libro fino como 'fuerza institucional'"],
    relatedEntryIds: ["gt_liq_definition", "gt_risk_slippage_concept"],
  }),
  ke({
    id: "gt_liq_iceberg_hypothesis",
    title: "Iceberg como hipótesis",
    category: "liquidity",
    kind: "HEURISTIC",
    concepts: ["iceberg", "hidden liquidity"],
    aliases: ["liquidez oculta"],
    statement: "La reposición repetida tras fills puede sugerir liquidez oculta; sigue siendo hipótesis.",
    explanation:
      "No se afirma iceberg por un solo refill. Se busca patrón y se mantiene invalidación (deja de reponer).",
    relatedEntryIds: ["gt_liq_persistence", "gt_of_absorption_central"],
  }),
  ke({
    id: "gt_liq_bid_ask_asymmetry",
    title: "Asimetría bid/ask",
    category: "liquidity",
    kind: "HEURISTIC",
    concepts: ["asimetría", "bid ask", "imbalance book"],
    aliases: ["book imbalance"],
    statement: "Asimetrías de libro son contexto de fricción, no señal direccional automática.",
    explanation:
      "Un bid dominante puede ser defensa, spoof o irrelevante si el flujo agresivo lo ignora.",
    prohibitedInterpretations: ["Más bids = precio sube"],
    relatedEntryIds: ["gt_liq_spoofing_hypothesis", "gt_of_aggression_vs_passive"],
  }),
  ke({
    id: "gt_liq_consumed_vs_defended",
    title: "Consumida vs defendida",
    category: "liquidity",
    kind: "RULE",
    concepts: ["liquidez consumida", "liquidez defendida", "consumed", "defended"],
    aliases: ["defense vs consumption"],
    statement: "Distinguir si la liquidez se consume (avanza el agresor) o se defiende (absorbe sin progreso).",
    explanation:
      "Esa distinción conecta liquidez con order flow y es más útil que el tamaño estático.",
    relatedEntryIds: ["gt_of_absorption_central", "gt_liq_persistence"],
  }),
  ke({
    id: "gt_liq_anti_size_only",
    title: "Anti-patrón: solo mirar tamaño",
    category: "liquidity",
    kind: "ANTI_PATTERN",
    concepts: ["tamaño", "size only", "solo size"],
    aliases: ["size worship"],
    statement: "Juzgar liquidez solo por el número en pantalla es un anti-patrón.",
    explanation:
      "Sin persistencia, interacción y flujo, el tamaño engaña. Spoofing y pulling existen precisamente por eso.",
    prohibitedInterpretations: ["El número más grande siempre gana"],
    relatedEntryIds: ["gt_liq_spoofing_hypothesis", "gt_liq_wall_not_reversal"],
  }),
  ke({
    id: "gt_liq_example_wall_fail",
    title: "Ejemplo: wall que falla",
    category: "liquidity",
    kind: "EXAMPLE",
    concepts: ["ejemplo wall", "wall fail"],
    aliases: ["caso wall fallida"],
    statement: "Ejemplo educativo: wall visible → pulling → continuación a través del nivel.",
    explanation:
      "Ilustra por qué wall ≠ reversión. El estudiante debe practicar invalidar la tesis de 'defensa' al ver retiros.",
    examples: ["Ask 500 lotes se retira; agresores cruzan; no hubo bounce."],
    relatedEntryIds: ["gt_liq_wall_not_reversal", "gt_liq_pulling"],
  }),
];
