import { ke, type GoodTradingKnowledgeEntry } from "./types";

export const ORDER_FLOW_ENTRIES: readonly GoodTradingKnowledgeEntry[] = [
  ke({
    id: "gt_of_definition",
    title: "Qué es order flow",
    category: "order_flow",
    kind: "DEFINITION",
    concepts: ["order flow", "orderflow", "flujo de órdenes"],
    aliases: ["tape reading educational"],
    statement: "Order flow estudia la interacción entre agresores y pasivos en el tiempo.",
    explanation:
      "No es magia predictiva: es lectura de presión, absorción, aceleración y fallo. En Mentor no se lee tu DOM en vivo.",
    relatedEntryIds: ["gt_of_aggression_vs_passive", "gt_of_absorption_central"],
  }),
  ke({
    id: "gt_of_aggression_vs_passive",
    title: "Agresor vs pasivo",
    category: "order_flow",
    kind: "DEFINITION",
    concepts: ["agresor", "pasivo", "aggressive", "passive"],
    aliases: ["taker vs maker"],
    statement: "El agresor cruza el spread; el pasivo espera ser hit.",
    explanation:
      "La narrativa 'quién gana' depende de si el agresor logra progreso o es absorbido. Esa es la base de absorption/continuation.",
    relatedEntryIds: ["gt_of_absorption_central", "gt_liq_consumed_vs_defended"],
  }),
  ke({
    id: "gt_of_absorption_central",
    title: "Absorption — regla central",
    category: "order_flow",
    kind: "RULE",
    concepts: ["absorption", "absorción"],
    aliases: ["absorbing flow"],
    statement:
      "Absorption: flujo agresivo significativo sin progreso direccional proporcional porque el pasivo absorbe.",
    explanation:
      "Es hipótesis operativa educativa: requiere evidencia de hits + falta de continuación + contexto de nivel. No se declara por un solo print.",
    confirmations: ["Pasivo se repone", "Delta/agresores no logran acceptance"],
    invalidations: ["El agresor logra acceptance y expansión"],
    prohibitedInterpretations: ["Cualquier stall = absorption"],
    relatedEntryIds: ["gt_of_absorption_vs_exhaustion", "gt_setup_absorption_fade", "gt_const_hypothesis_not_certainty"],
  }),
  ke({
    id: "gt_of_absorption_vs_exhaustion",
    title: "Absorption vs exhaustion",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["exhaustion", "agotamiento", "absorption vs exhaustion"],
    aliases: ["cansancio de flujo"],
    statement: "Exhaustion sugiere pérdida de agresividad; absorption sugiere defensa activa del pasivo.",
    explanation:
      "Se parecen en el chart pero difieren en mecanismo. Confundirlos cambia la invalidación.",
    relatedEntryIds: ["gt_of_absorption_central", "gt_of_initiative_vs_responsive"],
  }),
  ke({
    id: "gt_of_initiative_vs_responsive",
    title: "Iniciativa vs respuesta",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["iniciativa", "respuesta", "initiative", "responsive"],
    aliases: ["initiative flow"],
    statement: "Flujo de iniciativa busca acceptance; flujo responsive defiende o fadea.",
    explanation:
      "Heurística de auction market theory adaptada: ayuda a etiquetar intenciones relativas sin dogmatismo.",
    relatedEntryIds: ["gt_of_absorption_central", "gt_of_failed_auction"],
  }),
  ke({
    id: "gt_of_failed_auction",
    title: "Failed auction",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["failed auction", "subasta fallida"],
    aliases: ["failed breakout flow"],
    statement: "Una expansión que no logra acceptance puede fallar y rotar.",
    explanation:
      "Educativamente útil junto a sweep+reclaim. Sigue siendo hipótesis con invalidación clara (acceptance renovada).",
    relatedEntryIds: ["gt_liq_sweep_reclaim", "gt_setup_sweep_reclaim"],
  }),
  ke({
    id: "gt_of_delta_not_signal",
    title: "Delta no es señal automática",
    category: "order_flow",
    kind: "RULE",
    concepts: ["delta", "delta signal"],
    aliases: ["delta no compra"],
    statement: "Delta positivo/negativo no es por sí solo señal de compra/venta.",
    explanation:
      "Delta resume agresividad neta en una ventana. Sin ubicación, estructura y liquidez, es incompleto.",
    prohibitedInterpretations: ["Delta alcista = comprar", "Delta bajista = vender"],
    relatedEntryIds: ["gt_dc_delta_definition", "gt_const_context_over_signal"],
  }),
  ke({
    id: "gt_of_cvd_not_signal",
    title: "CVD no es señal automática",
    category: "order_flow",
    kind: "RULE",
    concepts: ["cvd", "cumulative volume delta"],
    aliases: ["cvd divergence magic"],
    statement: "CVD y sus divergencias son contexto; no mandatos automáticos.",
    explanation:
      "Divergencias pueden anticipar fatiga o ser ruido. Se leen con niveles y acceptance/rejection.",
    prohibitedInterpretations: ["Divergencia CVD = reversión segura"],
    relatedEntryIds: ["gt_dc_cvd_definition", "gt_dc_divergence_heuristic"],
  }),
  ke({
    id: "gt_of_footprint_role",
    title: "Rol del footprint",
    category: "order_flow",
    kind: "DEFINITION",
    concepts: ["footprint", "huella"],
    aliases: ["volume footprint"],
    statement: "El footprint organiza agresiones por precio; es herramienta de observación, no oráculo.",
    explanation:
      "Útil para ver imbalances y absorciones locales. En AI-2 Mentor no se conecta a footprint en vivo.",
    relatedEntryIds: ["gt_of_definition", "gt_of_absorption_central"],
  }),
  ke({
    id: "gt_of_dom_role",
    title: "Rol del DOM",
    category: "order_flow",
    kind: "DEFINITION",
    concepts: ["dom", "depth of market", "libro"],
    aliases: ["ladder"],
    statement: "El DOM muestra profundidad y dinámica pasiva/agresiva en tiempo real del operador.",
    explanation:
      "Educativamente: enseña pulling, stacking, spoofing-hypothesis. Este Mentor no lee tu DOM.",
    relatedEntryIds: ["gt_liq_pulling", "gt_liq_stacking", "gt_const_no_live_advice"],
  }),
  ke({
    id: "gt_of_imbalance",
    title: "Imbalance de flujo",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["imbalance", "desequilibrio"],
    aliases: ["stacked imbalance"],
    statement: "Imbalances muestran asimetría local de agresiones; requieren contexto de nivel.",
    explanation:
      "Una pila de imbalances puede acompañar tendencia o ser trampa en zona de liquidez opuesta.",
    prohibitedInterpretations: ["Imbalance = entrada market"],
    relatedEntryIds: ["gt_of_absorption_central", "gt_liq_wall_not_reversal"],
  }),
  ke({
    id: "gt_of_speed_of_tape",
    title: "Velocidad del tape",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["tape speed", "velocidad", "aceleración"],
    aliases: ["fast tape"],
    statement: "Aceleración del tape indica urgencia relativa, no dirección garantizada.",
    explanation:
      "Sirve para detectar iniciativa o pánico. Combinar con si hay acceptance o rechazo.",
    relatedEntryIds: ["gt_of_initiative_vs_responsive", "gt_liq_thin_book"],
  }),
  ke({
    id: "gt_of_acceptance_rejection",
    title: "Acceptance y rejection",
    category: "order_flow",
    kind: "RULE",
    concepts: ["acceptance", "rejection", "aceptación", "rechazo"],
    aliases: ["auction acceptance"],
    statement: "Acceptance = el mercado opera y sostiene un área; rejection = fallo de sostenerla.",
    explanation:
      "Conceptos puente entre precio y flujo. Muchas tesis (reclaim, breakout) viven o mueren aquí.",
    relatedEntryIds: ["gt_liq_sweep_reclaim", "gt_const_confirmation_is_evidence"],
  }),
  ke({
    id: "gt_of_trap_chase",
    title: "Anti-patrón: perseguir prints",
    category: "order_flow",
    kind: "ANTI_PATTERN",
    concepts: ["chase", "perseguir", "fomo flow"],
    aliases: ["chasing aggression"],
    statement: "Entrar solo porque 'el tape corre' sin nivel ni invalidación es anti-patrón.",
    explanation:
      "El chase convierte observación en impulso. El método exige ubicación y plan.",
    relatedEntryIds: ["gt_const_context_over_signal", "gt_risk_invalidation_first"],
  }),
  ke({
    id: "gt_of_example_absorb_at_level",
    title: "Ejemplo: absorción en nivel",
    category: "order_flow",
    kind: "EXAMPLE",
    concepts: ["ejemplo absorción"],
    aliases: ["caso absorption"],
    statement: "Ejemplo: agresores golpean un bid persistente sin acceptance bajista.",
    explanation:
      "Si además hay reclaim de un micro-nivel, la hipótesis de defensa gana peso — siempre con invalidación.",
    examples: ["Hits repetidos en zona + precio no hace LO; luego rotación alcista educativa."],
    relatedEntryIds: ["gt_of_absorption_central", "gt_setup_absorption_fade"],
  }),
  ke({
    id: "gt_of_unfinished_business",
    title: "Unfinished auction (heurística)",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["unfinished business", "subasta incompleta"],
    aliases: ["unfinished auction"],
    statement: "Zonas dejadas con desequilibrio pueden revisitarse; no es destino obligado.",
    explanation:
      "Heurística de 'asunto pendiente', no ley. Evitar usarla como predicción única.",
    prohibitedInterpretations: ["Siempre vuelve al imbalance"],
    relatedEntryIds: ["gt_of_imbalance", "gt_liq_magnet"],
  }),
  ke({
    id: "gt_of_news_spike_caution",
    title: "Spikes de noticia",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["news spike", "noticia", "spike"],
    aliases: ["event volatility flow"],
    statement: "En spikes de evento, el order flow se vuelve más ruidoso y menos transferable.",
    explanation:
      "El mentor recomienda humildad: spreads, thin books y prints extremos degradan lecturas habituales.",
    risks: ["Aplicar reglas de sesión normal a un spike de noticia"],
    relatedEntryIds: ["gt_liq_thin_book", "gt_const_insufficient_info"],
  }),
  ke({
    id: "gt_of_cross_with_gamma",
    title: "Order flow dentro de régimen gamma",
    category: "order_flow",
    kind: "HEURISTIC",
    concepts: ["order flow gamma", "flujo y gamma"],
    aliases: ["flow under gamma"],
    statement: "La misma lectura de flujo puede significar distinto bajo long vs short gamma (como hipótesis de régimen).",
    explanation:
      "Short gamma: más probabilidad de continuidad/expansión tras rupturas. Long gamma: más mean-reversion relativa. Siempre hipótesis.",
    relatedEntryIds: ["gt_gamma_pos_neg_hypothesis", "gt_cross_gamma_orderflow"],
  }),
];
