import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { pool } from "../../db";
import { ensureGoodTradingAccountForUser } from "../accounts/goodTradingAccountRepository";
import { createIntentWithInitialAttempt } from "./goodTradingOrderIntentRepository";
import { createReconciliationRun, findOrCreateBrokerObjectByReliableIdentities, getLatestReconciliationForAttempt, claimReconciliationAttempt, persistMatchedReconciliation } from "./goodTradingOrderReconciliationRepository";
import type { BrokerObservationSnapshot } from "../../../shared/durableOrderReconciliation";

const d = pool ? describe : describe.skip;
const snap: BrokerObservationSnapshot = { source: "ORDER_HISTORY", clientOrderId: "RACE-CLIENT", brokerOrderId: "987654321012345678", brokerOrderIdPrecisionTrusted: true, symbol: "BTC-USDT", side: "BUY", quantity: "1.000000000000000123", price: "65000.123456789012345", rawBrokerStatus: "OPEN", observedAt: new Date("2026-01-01T00:00:00Z") };
const makeInput = (accountUid: string, uid: string, key: string) => ({ intent: { logicalOrderUid: uid, goodTradingAccountUid: accountUid, executionBroker: "BINGX", executionEnvironment: "LIVE", executionMarketInstrument: "BTC-USDT", executionMarketVenue: "BINGX", executionMarketType: "Perpetual" as const, canonicalBaseAsset: "BTC", canonicalQuoteAsset: "USDT", canonicalSettlementAsset: "USDT", canonicalProductType: "Perpetual" as const, canonicalContractStyle: "Linear" as const, canonicalExpiry: null, sourceNativeSymbol: "BTC-USDT", sourceNativeInstrumentId: null, marketMetadataSource: "server-owned-v1-registry", marketMappingPolicy: "EXACT_V1_REGISTRY", requestedSide: "buy" as const, orderType: "LIMIT" as const, requestedSize: "1", requestedSizeUnit: "BTC" as const, requestedSizingMode: "quantity" as const, resolvedQuantity: "1", resolvedQuantityUnit: "BTC" as const, limitPrice: "65000.123456789012345", stopLossPrice: null, takeProfitPrice: null, timeInForce: "GTC" as const, postOnly: false, reduceOnly: false, requestIdempotencyKey: key }, attempt: { attemptId: `${uid}-ATTEMPT`, intentId: uid, attemptNumber: 1, brokerClientOrderId: "RACE-CLIENT", submittedQuantity: "1", transportState: "PERSISTED" as const, startedAt: null, responseAt: null, outcomeAt: null, reconciliationRequiredAt: null, brokerOrderId: null, rawBrokerStatus: null, httpStatus: null, errorCode: null, errorClass: null } });
async function fixture() { const marker = `${Date.now()}-${Math.random().toString(16).slice(2)}`; const u = await pool!.query("INSERT INTO users (email,password_hash,full_name) VALUES ($1,$2,$3) RETURNING id", [`race-${marker}@example.test`, "test", "B3-B3A-R3"]); const userId = Number(u.rows[0].id); const a = await ensureGoodTradingAccountForUser(userId); const uid = `GT-RACE-${marker}`; await createIntentWithInitialAttempt(makeInput(a.accountUid, uid, `race-key-${marker}`)); return { userId, accountUid: a.accountUid, uid, attemptId: `${uid}-ATTEMPT` }; }
async function cleanup(f: Awaited<ReturnType<typeof fixture>>) { await pool!.query("DELETE FROM goodtrading_broker_observation_snapshots WHERE broker_object_id IN (SELECT id FROM goodtrading_broker_objects WHERE broker_account_identity=$1)",[f.accountUid]); await pool!.query("DELETE FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$1",[f.accountUid]); await pool!.query("DELETE FROM goodtrading_broker_objects WHERE broker_account_identity=$1",[f.accountUid]); await pool!.query("DELETE FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1",[f.attemptId]); await pool!.query("DELETE FROM goodtrading_order_submission_attempts WHERE intent_id=$1",[f.uid]); await pool!.query("DELETE FROM goodtrading_order_intents WHERE id=$1",[f.uid]); await pool!.query("DELETE FROM goodtrading_accounts WHERE account_uid=$1",[f.accountUid]); await pool!.query("DELETE FROM users WHERE id=$1",[f.userId]); }

d("B3-B3A concurrency proofs", () => {
  it("converges GT and external workers to one account-scoped object", { timeout: 120000 }, async () => { const f = await fixture(); try { const run = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "race-generation", queriedSources: ["ORDER_HISTORY"] }); const barrier = Promise.all([new Promise<void>(r => setTimeout(r, 25)), new Promise<void>(r => setTimeout(r, 25))]); const results = await Promise.allSettled([barrier.then(() => findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: "RACE-CLIENT" }] })), barrier.then(() => persistMatchedReconciliation({ runId: run.id as string, brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: "RACE-CLIENT" }], attemptId: f.attemptId, intentId: f.uid, snapshot: snap }))]); assert.equal(results.filter(x => x.status === "rejected").length, 0); const c = await pool!.query("SELECT (SELECT count(*)::int FROM goodtrading_broker_objects WHERE broker_account_identity=$1) objects,(SELECT count(*)::int FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$1 AND identity_kind='CLIENT_ORDER_ID' AND identity_value='RACE-CLIENT') aliases",[f.accountUid]); assert.equal(c.rows[0].objects,1); assert.equal(c.rows[0].aliases,1); const object = await findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: "RACE-CLIENT" }] }); assert.equal(object.classification, "GT_LINKED"); } finally { await cleanup(f); } });
  it("selects one idempotent winner for concurrent claims", { timeout: 120000 }, async () => { const f = await fixture(); try { const claims = await Promise.allSettled([claimReconciliationAttempt(f.attemptId,"claim-generation",f.uid,f.uid),claimReconciliationAttempt(f.attemptId,"claim-generation",f.uid,f.uid)]); assert.equal(claims.filter(x => x.status === "rejected").length,0); const winners = claims.filter((x): x is PromiseFulfilledResult<{claimed:boolean;run:Record<string,unknown>}> => x.status === "fulfilled" && x.value.claimed); assert.equal(winners.length,1); const count = await pool!.query("SELECT count(*)::int AS n FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1 AND run_key=$2",[f.attemptId,"claim-generation"]); assert.equal(count.rows[0].n,1); assert.equal((await getLatestReconciliationForAttempt(f.attemptId))?.retry_authorized,false); } finally { await cleanup(f); } });
});
