import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { pool } from "../../db";
import { ensureGoodTradingAccountForUser } from "../accounts/goodTradingAccountRepository";
import { createIntentWithInitialAttempt } from "./goodTradingOrderIntentRepository";
import {
  completeReconciliationConflict,
  completeReconciliationMatched,
  completeReconciliationNoMatch,
  completeReconciliationUnresolved,
  createReconciliationRun,
  findBrokerObjectByReliableIdentity,
  findOrCreateBrokerObjectByReliableIdentities,
  getLatestReconciliationForAttempt,
  linkBrokerObjectToAttempt,
  listAttemptsRequiringReconciliation,
  persistMatchedReconciliation,
  recordBrokerObservation,
} from "./goodTradingOrderReconciliationRepository";
import type { BrokerObservationSnapshot } from "../../../shared/durableOrderReconciliation";

const suite = pool ? describe : describe.skip;
const snapshot = (status: string, clientOrderId = "GT-CLIENT-B3B3A", brokerOrderId?: string): BrokerObservationSnapshot => ({ source: "ORDER_HISTORY", clientOrderId, brokerOrderId, brokerOrderIdPrecisionTrusted: !!brokerOrderId, symbol: "BTC-USDT", side: "BUY", quantity: "0.000000000000000123", price: "65000.123456789012345", rawBrokerStatus: status, sourceTimestamp: new Date("2026-01-01T00:00:00Z"), observedAt: new Date("2026-01-01T00:00:01Z") });
const input = (accountUid: string, uid: string, key: string, client = `${uid}-CLIENT`) => ({ intent: { logicalOrderUid: uid, goodTradingAccountUid: accountUid, executionBroker: "BINGX", executionEnvironment: "LIVE", executionMarketInstrument: "BTC-USDT", executionMarketVenue: "BINGX", executionMarketType: "Perpetual" as const, canonicalBaseAsset: "BTC", canonicalQuoteAsset: "USDT", canonicalSettlementAsset: "USDT", canonicalProductType: "Perpetual" as const, canonicalContractStyle: "Linear" as const, canonicalExpiry: null, sourceNativeSymbol: "BTC-USDT", sourceNativeInstrumentId: null, marketMetadataSource: "server-owned-v1-registry", marketMappingPolicy: "EXACT_V1_REGISTRY", requestedSide: "buy" as const, orderType: "LIMIT" as const, requestedSize: "0.000000000000000123", requestedSizeUnit: "BTC" as const, requestedSizingMode: "quantity" as const, resolvedQuantity: "0.000000000000000123", resolvedQuantityUnit: "BTC" as const, limitPrice: "65000.123456789012345", stopLossPrice: null, takeProfitPrice: null, timeInForce: "GTC" as const, postOnly: false, reduceOnly: false, requestIdempotencyKey: key }, attempt: { attemptId: `${uid}-ATTEMPT`, intentId: uid, attemptNumber: 1, brokerClientOrderId: client, submittedQuantity: "0.000000000000000123", transportState: "PERSISTED" as const, startedAt: null, responseAt: null, outcomeAt: null, reconciliationRequiredAt: null, brokerOrderId: null, rawBrokerStatus: null, httpStatus: null, errorCode: null, errorClass: null } });
async function fixture() { const marker = `${Date.now()}-${Math.random().toString(16).slice(2)}`; const user = await pool!.query("INSERT INTO users (email,password_hash,full_name) VALUES ($1,$2,$3) RETURNING id", [`b3b3a-${marker}@example.test`, "test", "B3-B3A-R2"]); const userId = Number(user.rows[0].id); const account = await ensureGoodTradingAccountForUser(userId); const uid = `GT-B3B3A-${marker}`; await createIntentWithInitialAttempt(input(account.accountUid, uid, `key-${marker}`)); return { userId, accountUid: account.accountUid, uid, attemptId: `${uid}-ATTEMPT`, client: `${uid}-CLIENT` }; }
async function cleanup(f: Awaited<ReturnType<typeof fixture>>) { await pool!.query("DELETE FROM goodtrading_broker_observation_snapshots WHERE broker_object_id IN (SELECT id FROM goodtrading_broker_objects WHERE broker_account_identity=$1)", [f.accountUid]); await pool!.query("DELETE FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$1", [f.accountUid]); await pool!.query("DELETE FROM goodtrading_broker_objects WHERE broker_account_identity=$1", [f.accountUid]); await pool!.query("DELETE FROM goodtrading_order_reconciliation_runs WHERE attempt_id=$1", [f.attemptId]); await pool!.query("DELETE FROM goodtrading_order_submission_attempts WHERE intent_id=$1", [f.uid]); await pool!.query("DELETE FROM goodtrading_order_intents WHERE id=$1", [f.uid]); await pool!.query("DELETE FROM goodtrading_accounts WHERE account_uid=$1", [f.accountUid]); await pool!.query("DELETE FROM users WHERE id=$1", [f.userId]); }

suite("B3-B3A durable PostgreSQL foundation", () => {
  it("enforces run safety, idempotency, and all completion results", { timeout: 120000 }, async () => { const f = await fixture(); try { const run = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "generation-1", queriedSources: ["OPEN_ORDERS", "ORDER_HISTORY"] }); await assert.rejects(() => createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "generation-1", queriedSources: [] })); await completeReconciliationMatched(run.id as string); const conflictRun = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "generation-2", queriedSources: ["ORDER_HISTORY"] }); await completeReconciliationConflict(conflictRun.id as string, { conflictReasons: ["SIDE_MISMATCH"] }); const noRun = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "generation-3", queriedSources: ["OPEN_ORDERS"] }); await completeReconciliationNoMatch(noRun.id as string); const unresolved = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "generation-4", queriedSources: ["FILL_HISTORY"] }); await completeReconciliationUnresolved(unresolved.id as string, { sourceStatuses: { FILL_HISTORY: "failed" }, sourceErrorCodes: ["BINGX_TIMEOUT"] }); const unsafe = await pool!.query("INSERT INTO goodtrading_order_reconciliation_runs (id,attempt_id,intent_id,logical_order_uid,run_key,run_status,started_at,absence_proven,retry_authorized) VALUES ('unsafe-a',$1,$2,$2,'unsafe','STARTED',now(),true,false)", [f.attemptId, f.uid]).catch((e) => e); assert.equal((unsafe as {code?: string}).code, "23514"); const latest = await getLatestReconciliationForAttempt(f.attemptId); assert.equal(latest?.result, "UNRESOLVED"); } finally { await cleanup(f); } });

  it("converges aliases, preserves snapshots, and promotes external to GT once", { timeout: 120000 }, async () => { const f = await fixture(); try { const a = await findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: f.client }] }); const b = await findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: f.client }, { kind: "TRUSTED_BROKER_ORDER_ID", value: "987654321012345678", precisionTrusted: true }, { kind: "EXECUTION_ID", value: "fill-1" }] }); assert.equal(a.id, b.id); assert.equal((await findBrokerObjectByReliableIdentity(f.accountUid, { kind: "TRUSTED_BROKER_ORDER_ID", value: "987654321012345678", precisionTrusted: true }))?.id, a.id); await recordBrokerObservation({ brokerObjectId: a.id, snapshot: snapshot("OPEN") }); await recordBrokerObservation({ brokerObjectId: a.id, snapshot: snapshot("PARTIALLY_FILLED", f.client, "987654321012345678") }); await recordBrokerObservation({ brokerObjectId: a.id, snapshot: snapshot("FILLED", f.client, "987654321012345678") }); const counts = await pool!.query("SELECT (SELECT count(*) FROM goodtrading_broker_objects WHERE broker_account_identity=$1) objects,(SELECT count(*) FROM goodtrading_broker_observation_snapshots WHERE broker_object_id=$2) snapshots", [f.accountUid, a.id]); assert.equal(Number(counts.rows[0].objects), 1); assert.equal(Number(counts.rows[0].snapshots), 3); const promoted = await linkBrokerObjectToAttempt({ brokerObjectId: a.id, brokerAccountIdentity: f.accountUid, attemptId: f.attemptId, intentId: f.uid }); assert.equal(promoted.classification, "GT_LINKED"); await assert.rejects(() => linkBrokerObjectToAttempt({ brokerObjectId: a.id, brokerAccountIdentity: f.accountUid, attemptId: "other-attempt", intentId: "other-intent" })); } finally { await cleanup(f); } });

  it("keeps account identity isolated and rejects numeric reliable identity", { timeout: 120000 }, async () => { const f = await fixture(); try { const a = await findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: "SAME-ID" }] }); const other = await findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: `${f.accountUid}-OTHER`, identities: [{ kind: "CLIENT_ORDER_ID", value: "SAME-ID" }] }); assert.notEqual(a.id, other.id); await assert.rejects(() => findOrCreateBrokerObjectByReliableIdentities({ brokerAccountIdentity: f.accountUid, identities: [{ kind: "TRUSTED_BROKER_ORDER_ID", value: "123", precisionTrusted: false }] })); const numeric = await recordBrokerObservation({ brokerObjectId: a.id, snapshot: { ...snapshot("NEW", "SAME-ID", "123"), brokerOrderIdPrecisionTrusted: false } }); assert.equal(numeric.broker_order_id_precision_trusted, false); const aliases = await pool!.query("SELECT count(*)::int AS n FROM goodtrading_broker_identity_aliases WHERE broker_account_identity=$1 AND identity_value='123'", [f.accountUid]); assert.equal(aliases.rows[0].n, 0); await pool!.query("DELETE FROM goodtrading_broker_observation_snapshots WHERE broker_object_id=$1", [other.id]); await pool!.query("DELETE FROM goodtrading_broker_identity_aliases WHERE broker_object_id=$1", [other.id]); await pool!.query("DELETE FROM goodtrading_broker_objects WHERE id=$1", [other.id]); } finally { await cleanup(f); } });

  it("persists atomic MATCHED evidence and rolls back on missing run", { timeout: 120000 }, async () => { const f = await fixture(); try { const run = await createReconciliationRun({ attemptId: f.attemptId, intentId: f.uid, logicalOrderUid: f.uid, runKey: "matched-1", queriedSources: ["ORDER_HISTORY"] }); const object = await persistMatchedReconciliation({ runId: run.id as string, brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: f.client }], attemptId: f.attemptId, intentId: f.uid, snapshot: snapshot("OPEN") }); assert.equal(object.classification, "GT_LINKED"); const before = await pool!.query("SELECT count(*)::int AS n FROM goodtrading_broker_objects WHERE broker_account_identity=$1", [f.accountUid]); await assert.rejects(() => persistMatchedReconciliation({ runId: "missing-run", brokerAccountIdentity: f.accountUid, identities: [{ kind: "CLIENT_ORDER_ID", value: `${f.client}-rollback` }], attemptId: f.attemptId, intentId: f.uid, snapshot: snapshot("OPEN", `${f.client}-rollback`) })); const after = await pool!.query("SELECT count(*)::int AS n FROM goodtrading_broker_objects WHERE broker_account_identity=$1", [f.accountUid]); assert.equal(after.rows[0].n, before.rows[0].n); } finally { await cleanup(f); } });

  it("lists only reconciliation-eligible transport states", { timeout: 120000 }, async () => { const f = await fixture(); try { await pool!.query("UPDATE goodtrading_order_submission_attempts SET transport_state='SUBMISSION_STARTED',started_at=now()-interval '61 seconds' WHERE id=$1", [f.attemptId]); const eligible = await listAttemptsRequiringReconciliation(); assert.ok(eligible.some((row) => row.id === f.attemptId)); await pool!.query("UPDATE goodtrading_order_submission_attempts SET started_at=now() WHERE id=$1", [f.attemptId]); assert.ok(!(await listAttemptsRequiringReconciliation()).some((row) => row.id === f.attemptId)); await pool!.query("UPDATE goodtrading_order_submission_attempts SET transport_state='PERSISTED',started_at=null WHERE id=$1", [f.attemptId]); assert.ok(!(await listAttemptsRequiringReconciliation()).some((row) => row.id === f.attemptId)); } finally { await cleanup(f); } });
});
