import type { EconomicFillRecord } from "./economicFill";
import type { DurableGoodTradingOrderIntent, DurableSubmissionAttempt } from "./durableOrderIntent";

export type ExecutionQualityLatency = Readonly<{ decisionToSubmissionStart: number | null; submissionStartToBrokerResponse: number | null; decisionToBrokerResponse: number | null; decisionToFirstFill: number | null; decisionToTerminalFill: number | null }>;
export type ExecutionQualityFillCompleteness = "COMPLETE" | "PARTIAL" | "UNAVAILABLE" | "CONFLICT";
export type ExecutionQualityEvidenceStatus = "COMPLETE" | "PARTIAL" | "UNAVAILABLE" | "CONFLICT";
export type ExecutionQualityFeeEvidence = Readonly<{ perFill: readonly Readonly<{ executionId: string; amount: string; asset: string }>[]; aggregates: readonly Readonly<{ asset: string; amount: string }>[]; evidence: "FACTUAL" | "PARTIAL" | "UNAVAILABLE" | "CONFLICT" }>;
export type OrderExecutionQuality = Readonly<{ requestedLimitPrice: string; latencyMs: ExecutionQualityLatency; quantities: Readonly<{ requested: string; submitted: string | null; factualFilled: string | null }>; factualExecutionVwap: string | null; vwapVsRequestedLimit: Readonly<{ absolute: string | null; percent: string | null }>; fees: ExecutionQualityFeeEvidence; fillCompleteness: ExecutionQualityFillCompleteness; evidenceStatus: ExecutionQualityEvidenceStatus; evidenceGaps: readonly string[] }>;
export type OrderExecutionQualityInput = Readonly<{ intent: Pick<DurableGoodTradingOrderIntent, "requestedSize" | "resolvedQuantity" | "limitPrice" | "decisionEvidence">; attempts: readonly Pick<DurableSubmissionAttempt, "attemptNumber" | "submittedQuantity" | "startedAt" | "responseAt">[]; lifecycleStatus: "OPEN" | "PARTIALLY_FILLED" | "FILLED" | "CANCELED" | "REJECTED" | "EXPIRED"; fills: readonly EconomicFillRecord[]; fillCompleteness: ExecutionQualityFillCompleteness }>;

type Decimal = { units: any; scale: number };
const bigInt = (value: string | number): any => (globalThis as any).BigInt(value);
function decimalText(value: string | number): string { const raw = String(value); if (!/[eE]/.test(raw)) return raw; return Number(value).toFixed(18).replace(/0+$/, "").replace(/\.$/, ""); }
function parse(value: string | number): Decimal { const text = decimalText(value); const [whole, fraction = ""] = text.split("."); return { units: bigInt(`${whole}${fraction}`), scale: fraction.length }; }
function align(a: Decimal, b: Decimal): [any, any, number] { const scale = Math.max(a.scale, b.scale); return [a.units * (bigInt(10) ** bigInt(scale - a.scale)), b.units * (bigInt(10) ** bigInt(scale - b.scale)), scale]; }
function add(a: Decimal, b: Decimal): Decimal { const [x, y, scale] = align(a, b); return { units: x + y, scale }; }
function compare(a: Decimal, b: Decimal): number { const [x, y] = align(a, b); return x < y ? -1 : x > y ? 1 : 0; }
function multiply(a: Decimal, b: Decimal): Decimal { return { units: a.units * b.units, scale: a.scale + b.scale }; }
function divide(a: Decimal, b: Decimal, places = 18): Decimal { return { units: (a.units * (bigInt(10) ** bigInt(places + b.scale))) / b.units, scale: a.scale + places }; }
function format(value: Decimal): string { const negative = value.units < bigInt(0); const raw = (negative ? -value.units : value.units).toString().padStart(value.scale + 1, "0"); const whole = value.scale ? raw.slice(0, -value.scale) : raw; const fraction = value.scale ? raw.slice(-value.scale).replace(/0+$/, "") : ""; return `${negative ? "-" : ""}${whole}${fraction ? `.${fraction}` : ""}`; }
function time(value: Date | null | undefined): number | null { return value instanceof Date && Number.isFinite(value.getTime()) ? value.getTime() : null; }
function duration(end: number | null, start: number | null): number | null { return end === null || start === null ? null : end < start ? null : end - start; }
function sameFillFacts(a: EconomicFillRecord, b: EconomicFillRecord): boolean { return JSON.stringify(a) === JSON.stringify(b); }
function uniqueFills(fills: readonly EconomicFillRecord[]): { fills: EconomicFillRecord[]; conflicts: string[] } { const byId = new Map<string, EconomicFillRecord>(); const conflicts: string[] = []; for (const fill of fills) { const key = fill.executionId; const previous = byId.get(key); if (!previous) byId.set(key, fill); else if (!sameFillFacts(previous, fill)) conflicts.push(`CONFLICTING_EXECUTION_ID:${fill.executionId}`); } return { fills: Array.from(byId.values()), conflicts }; }

export function buildOrderExecutionQuality(input: OrderExecutionQualityInput): OrderExecutionQuality {
  const evidenceGaps: string[] = []; const decision = time(input.intent.decisionEvidence?.decisionAt); if (decision === null) evidenceGaps.push("MISSING_DECISION_AT");
  const attempt = [...input.attempts].sort((a, b) => a.attemptNumber - b.attemptNumber)[0]; const started = time(attempt?.startedAt); const response = time(attempt?.responseAt); if (started === null) evidenceGaps.push("MISSING_SUBMISSION_START"); if (response === null) evidenceGaps.push("MISSING_BROKER_RESPONSE");
  const deduped = uniqueFills(input.fills); evidenceGaps.push(...deduped.conflicts); const fills = deduped.fills.sort((a, b) => a.eventTime - b.eventTime || a.executionId.localeCompare(b.executionId)); const conflict = deduped.conflicts.length > 0 || input.fillCompleteness === "CONFLICT";
  if (conflict) evidenceGaps.push("FILL_EVIDENCE_CONFLICT");
  const invalidTime = (started !== null && response !== null && response < started) || (decision !== null && started !== null && started < decision) || (decision !== null && fills.some(fill => fill.eventTime < decision)); if (invalidTime) evidenceGaps.push("INVALID_TIMESTAMP_ORDER");
  const filled = fills.reduce((total, fill) => add(total, parse(fill.quantity)), { units: bigInt(0), scale: 0 }); const hasFills = fills.length > 0; const complete = input.fillCompleteness === "COMPLETE" && !conflict && !invalidTime;
  if (!hasFills) evidenceGaps.push("MISSING_FILL_EVIDENCE"); if (input.fillCompleteness !== "COMPLETE" && hasFills) evidenceGaps.push("FILL_HISTORY_NOT_COMPLETE");
  let vwap: string | null = null; let weighted = { units: bigInt(0), scale: 0 }; for (const fill of fills) weighted = add(weighted, multiply(parse(fill.quantity), parse(fill.price))); if (complete && filled.units > bigInt(0)) vwap = format(divide(weighted, filled));
  const limit = parse(input.intent.limitPrice); const deviation = vwap === null ? { absolute: null, percent: null } : (() => { const diff = add(parse(vwap), { units: -limit.units, scale: limit.scale }); return { absolute: format(diff), percent: format(divide(multiply(diff, { units: bigInt(100), scale: 0 }), limit)) }; })(); if (vwap === null) evidenceGaps.push("COMPLETE_VWAP_UNAVAILABLE");
  const feeRows = fills.filter(fill => fill.fee?.value != null && fill.fee.currency).map(fill => ({ executionId: fill.executionId, amount: format(parse(fill.fee!.value!)), asset: fill.fee!.currency! })); const grouped = new Map<string, Decimal>(); for (const fee of feeRows) grouped.set(fee.asset, add(grouped.get(fee.asset) ?? { units: bigInt(0), scale: 0 }, parse(fee.amount))); const aggregates = Array.from(grouped.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([asset, amount]) => ({ asset, amount: format(amount) })); const feeEvidence = conflict ? "CONFLICT" : feeRows.length === 0 ? "UNAVAILABLE" : !complete ? "PARTIAL" : feeRows.length === fills.length ? "FACTUAL" : "PARTIAL"; if (feeEvidence === "UNAVAILABLE") evidenceGaps.push("MISSING_FEE_EVIDENCE"); if (feeEvidence === "PARTIAL") evidenceGaps.push("PARTIAL_FEE_EVIDENCE");
  const evidenceStatus: ExecutionQualityEvidenceStatus = conflict || invalidTime ? "CONFLICT" : decision === null && !hasFills ? "UNAVAILABLE" : evidenceGaps.length ? "PARTIAL" : "COMPLETE";
  return { requestedLimitPrice: input.intent.limitPrice, latencyMs: { decisionToSubmissionStart: invalidTime ? null : duration(started, decision), submissionStartToBrokerResponse: invalidTime ? null : duration(response, started), decisionToBrokerResponse: invalidTime ? null : duration(response, decision), decisionToFirstFill: complete && fills[0] ? duration(fills[0].eventTime, decision) : null, decisionToTerminalFill: complete && fills.length ? duration(fills.at(-1)!.eventTime, decision) : null }, quantities: { requested: input.intent.resolvedQuantity, submitted: attempt?.submittedQuantity == null ? null : String(attempt.submittedQuantity), factualFilled: conflict ? null : format(filled) }, factualExecutionVwap: vwap, vwapVsRequestedLimit: deviation, fees: { perFill: feeRows, aggregates, evidence: feeEvidence }, fillCompleteness: conflict ? "CONFLICT" : input.fillCompleteness, evidenceStatus, evidenceGaps: Array.from(new Set(evidenceGaps)) };
}
